<a href="https://colab.research.google.com/github/Cyril-19/Cyril-19/blob/main/absenteeism_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [249]:
import pandas as pd

In [250]:
df1=pd.read_csv("/content/Absenteeism_data.csv")
df1

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,3,23,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,10,22,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,20,23,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,14,19,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,1,22,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,20,1,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,20,1,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,20,11,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,3,11,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,24,14,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,3,23,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,3,21,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,6,11,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,33,23,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,18,10,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,3,11,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,10,13,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,20,28,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,11,18,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,10,25,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,11,23,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,30,28,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,11,18,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,3,23,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,3,18,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,2,18,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,1,23,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,2,18,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,3,23,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,10,23,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,11,24,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,19,11,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,2,28,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,20,23,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,27,23,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,34,23,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,3,23,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,5,19,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,14,23,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,34,23,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,3,23,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,15,23,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,20,22,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,15,14,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,20,0,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,29,0,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,28,23,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,34,23,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,11,0,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,36,0,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,28,18,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,3,23,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,13,0,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,33,23,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,3,23,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,20,23,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,3,23,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,34,23,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,36,0,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,22,23,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,3,23,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,28,23,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,34,23,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,28,23,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,33,23,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,15,23,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,3,23,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,28,23,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,20,19,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,15,14,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,28,28,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,11,26,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,10,23,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,20,28,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,3,23,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,28,23,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,3,13,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,17,21,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,15,23,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,14,10,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,6,22,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,15,14,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,14,6,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,17,21,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,28,13,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,20,28,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,33,28,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,28,28,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,11,7,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,15,23,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,33,23,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,34,19,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,36,23,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,1,26,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,28,23,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,20,26,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,34,19,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,10,22,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,28,28,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,20,28,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,28,23,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,10,22,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,34,27,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,24,19,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,28,23,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,28,23,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,34,19,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,34,27,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,14,18,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,28,27,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,27,23,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,28,28,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,28,27,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,28,27,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,34,27,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,34,27,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,22,18,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,11,18,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,27,23,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,34,27,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,34,27,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,28,23,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,11,22,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,27,23,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,24,1,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,3,11,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,14,28,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,6,23,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,20,28,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,11,22,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,31,11,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,31,1,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,28,28,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,28,23,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,22,23,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,27,23,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,28,25,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,18,18,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,18,23,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,28,23,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,6,19,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,19,28,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,20,19,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,30,19,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,17,17,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,15,22,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,20,13,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,22,13,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,33,14,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,20,13,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,17,11,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,14,1,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,20,26,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,14,13,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,11,6,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,17,8,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,20,28,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,28,23,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,7,14,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,3,13,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,28,23,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,28,11,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,22,13,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,28,11,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,28,11,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,3,13,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,7,14,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,28,28,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,33,14,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,28,28,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,15,28,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,28,23,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,14,28,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,24,13,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,14,23,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,28,28,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,20,28,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,3,13,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,36,23,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,15,23,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,24,14,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,15,28,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,33,28,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,20,19,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,11,19,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,14,12,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,23,19,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,11,13,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,1,7,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,2,0,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,14,28,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,14,28,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,3,18,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,28,19,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,27,7,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,14,28,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,3,12,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,7,0,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,18,0,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,23,0,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,31,0,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,3,11,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,36,13,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,10,22,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,24,19,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,10,22,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,24,10,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,15,23,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,24,10,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,3,11,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,14,23,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,24,10,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,36,13,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,1,13,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,36,23,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,36,13,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,23,22,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,3,11,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,32,28,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,28,28,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,14,19,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,36,1,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,34,5,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,34,26,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,18,26,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,22,18,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,14,25,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,18,1,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,18,1,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,30,25,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,10,22,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,11,26,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,3,26,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,11,19,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,11,19,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,20,0,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,11,19,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,30,19,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,11,23,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,9,18,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,26,13,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,26,14,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,20,28,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,11,23,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,33,23,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,21,11,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,22,23,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,36,13,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,33,25,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,1,23,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,36,23,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,1,19,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,10,8,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,27,6,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,3,11,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,3,23,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,11,19,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,5,0,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,24,9,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,15,28,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,8,0,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,19,0,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,3,13,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,24,9,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,3,23,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,20,28,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,5,26,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,36,28,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,5,0,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,15,7,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,3,13,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,11,24,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,1,26,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,11,26,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,11,22,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,36,0,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,33,0,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,22,1,12/10/2016,179,26,30,265.017,19,3,0,0,8
296,34,7,12/10/2016,118,10,37,265.017,28,1,0,0,3
297,13,22,12/10/2016,369,17,31,265.017,25,1,3,0,8
298,3,28,14/10/2016,179,51,38,265.017,31,1,0,0,1
299,22,1,14/10/2016,179,26,30,265.017,19,3,0,0,64
300,5,0,14/10/2016,235,20,43,265.017,38,1,1,0,0
301,11,19,15/10/2016,289,36,33,265.017,30,1,2,1,16
302,20,28,16/10/2016,260,50,36,265.017,23,1,4,0,3
303,5,0,16/10/2016,235,20,43,265.017,38,1,1,0,0
304,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
305,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
306,36,28,20/10/2016,118,13,50,265.017,31,1,1,0,1
307,15,28,20/10/2016,291,31,40,265.017,25,1,1,1,4
308,22,23,22/10/2016,179,26,30,265.017,19,3,0,0,16
309,36,28,22/10/2016,118,13,50,265.017,31,1,1,0,1
310,10,10,26/10/2016,361,52,28,265.017,27,1,1,4,8
311,20,0,27/10/2016,260,50,36,265.017,23,1,4,0,0
312,15,0,27/10/2016,291,31,40,265.017,25,1,1,1,0
313,30,0,27/10/2016,157,27,29,265.017,22,1,0,0,0
314,22,1,28/10/2016,179,26,30,265.017,19,3,0,0,5
315,22,7,28/10/2016,179,26,30,265.017,19,3,0,0,5
316,36,23,29/10/2016,118,13,50,265.017,31,1,1,0,1
317,34,11,07/11/2016,118,10,37,284.031,28,1,0,0,8
318,33,23,07/11/2016,248,25,47,284.031,32,1,2,1,2
319,3,6,08/11/2016,179,51,38,284.031,31,1,0,0,8
320,20,28,11/11/2016,260,50,36,284.031,23,1,4,0,3
321,15,23,14/11/2016,291,31,40,284.031,25,1,1,1,1
322,23,1,14/11/2016,378,49,36,284.031,21,1,2,4,8
323,14,11,14/11/2016,155,12,34,284.031,25,1,2,0,120
324,5,26,14/11/2016,235,20,43,284.031,38,1,1,0,8
325,18,0,15/11/2016,330,16,28,284.031,25,2,0,0,0
326,1,18,16/11/2016,235,11,37,284.031,29,3,1,1,1
327,34,11,16/11/2016,118,10,37,284.031,28,1,0,0,3
328,1,25,17/11/2016,235,11,37,284.031,29,3,1,1,2
329,3,28,17/11/2016,179,51,38,284.031,31,1,0,0,3
330,24,13,18/11/2016,246,25,41,284.031,23,1,0,0,8
331,15,12,18/11/2016,291,31,40,284.031,25,1,1,1,4
332,24,13,21/11/2016,246,25,41,284.031,23,1,0,0,8
333,3,28,22/11/2016,179,51,38,284.031,31,1,0,0,1
334,20,10,23/11/2016,260,50,36,284.031,23,1,4,0,8
335,20,15,25/11/2016,260,50,36,284.031,23,1,4,0,8
336,23,0,25/11/2016,378,49,36,284.031,21,1,2,4,0
337,7,0,29/11/2016,279,5,39,284.031,24,1,2,0,0
338,3,23,24/11/2016,179,51,38,284.031,31,1,0,0,1
339,28,12,05/12/2016,225,26,28,236.629,24,1,1,2,3
340,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,2
341,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,1
342,1,23,05/12/2016,235,11,37,236.629,29,3,1,1,3
343,36,28,06/12/2016,118,13,50,236.629,31,1,1,0,1
344,20,28,09/12/2016,260,50,36,236.629,23,1,4,0,4
345,24,4,15/12/2016,246,25,41,236.629,23,1,0,0,8
346,3,28,15/12/2016,179,51,38,236.629,31,1,0,0,1
347,3,28,16/12/2016,179,51,38,236.629,31,1,0,0,1
348,22,23,20/12/2016,179,26,30,236.629,19,3,0,0,1
349,34,25,20/12/2016,118,10,37,236.629,28,1,0,0,8
350,1,25,22/12/2016,235,11,37,236.629,29,3,1,1,2
351,3,28,23/12/2016,179,51,38,236.629,31,1,0,0,1
352,5,13,20/12/2016,235,20,43,236.629,38,1,1,0,8
353,1,14,20/12/2016,235,11,37,236.629,29,3,1,1,4
354,20,26,21/12/2016,260,50,36,236.629,23,1,4,0,8
355,30,28,19/12/2016,157,27,29,236.629,22,1,0,0,2
356,3,28,19/12/2016,179,51,38,236.629,31,1,0,0,3
357,11,19,19/12/2016,289,36,33,236.629,30,1,2,1,8
358,28,23,04/01/2017,225,26,28,330.061,24,1,1,2,5
359,34,19,09/01/2017,118,10,37,330.061,28,1,0,0,32
360,14,23,09/01/2017,155,12,34,330.061,25,1,2,0,2
361,1,13,03/01/2017,235,11,37,330.061,29,3,1,1,1
362,14,23,03/01/2017,155,12,34,330.061,25,1,2,0,4
363,11,26,09/01/2017,289,36,33,330.061,30,1,2,1,8
364,15,3,11/01/2017,291,31,40,330.061,25,1,1,1,8
365,5,26,16/01/2017,235,20,43,330.061,38,1,1,0,8
366,36,26,16/01/2017,118,13,50,330.061,31,1,1,0,4
367,3,28,25/01/2017,179,51,38,330.061,31,1,0,0,1
368,3,28,27/01/2017,179,51,38,330.061,31,1,0,0,1
369,34,28,07/02/2017,118,10,37,251.818,28,1,0,0,2
370,3,27,01/02/2017,179,51,38,251.818,31,1,0,0,3
371,28,7,01/02/2017,225,26,28,251.818,24,1,1,2,1
372,11,22,03/02/2017,289,36,33,251.818,30,1,2,1,3
373,20,28,10/02/2017,260,50,36,251.818,23,1,4,0,3
374,3,23,17/02/2017,179,51,38,251.818,31,1,0,0,3
375,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,2
376,3,27,15/02/2017,179,51,38,251.818,31,1,0,0,3
377,3,10,16/02/2017,179,51,38,251.818,31,1,0,0,8
378,24,26,16/02/2017,246,25,41,251.818,23,1,0,0,8
379,3,27,17/02/2017,179,51,38,251.818,31,1,0,0,3
380,6,22,13/02/2017,189,29,33,251.818,25,1,2,2,8
381,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,3
382,24,23,21/02/2017,246,25,41,251.818,23,1,0,0,2
383,15,23,21/02/2017,291,31,40,251.818,25,1,1,1,2
384,30,11,22/02/2017,157,27,29,251.818,22,1,0,0,16
385,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
386,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
387,24,10,24/02/2017,246,25,41,251.818,23,1,0,0,24
388,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
389,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
390,34,18,07/03/2017,118,10,37,244.387,28,1,0,0,8
391,24,19,08/03/2017,246,25,41,244.387,23,1,0,0,16
392,24,28,10/03/2017,246,25,41,244.387,23,1,0,0,2
393,20,28,10/03/2017,260,50,36,244.387,23,1,4,0,4
394,3,28,13/03/2017,179,51,38,244.387,31,1,0,0,2
395,1,22,13/03/2017,235,11,37,244.387,29,3,1,1,8
396,17,22,14/03/2017,179,22,40,244.387,22,2,2,0,8
397,23,22,14/03/2017,378,49,36,244.387,21,1,2,4,8
398,3,28,20/03/2017,179,51,38,244.387,31,1,0,0,16
399,10,22,22/03/2017,361,52,28,244.387,27,1,1,4,8
400,13,0,22/03/2017,369,17,31,244.387,25,1,3,0,0

In [251]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    object
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB

In [252]:
pd.options.display.max_columns=None
pd.options.display.max_rows=None

In [253]:
df=df1.copy()
df

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,3,23,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,10,22,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,20,23,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,14,19,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,1,22,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,20,1,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,20,1,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,20,11,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,3,11,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,24,14,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,3,23,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,3,21,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,6,11,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,33,23,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,18,10,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,3,11,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,10,13,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,20,28,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,11,18,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,10,25,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,11,23,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,30,28,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,11,18,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,3,23,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,3,18,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,2,18,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,1,23,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,2,18,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,3,23,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,10,23,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,11,24,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,19,11,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,2,28,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,20,23,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,27,23,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,34,23,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,3,23,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,5,19,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,14,23,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,34,23,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,3,23,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,15,23,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,20,22,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,15,14,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,20,0,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,29,0,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,28,23,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,34,23,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,11,0,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,36,0,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,28,18,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,3,23,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,13,0,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,33,23,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,3,23,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,20,23,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,3,23,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,34,23,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,36,0,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,22,23,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,3,23,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,28,23,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,34,23,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,28,23,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,33,23,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,15,23,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,3,23,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,28,23,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,20,19,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,15,14,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,28,28,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,11,26,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,10,23,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,20,28,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,3,23,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,28,23,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,3,13,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,17,21,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,15,23,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,14,10,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,6,22,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,15,14,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,14,6,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,28,23,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,17,21,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,28,13,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,20,28,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,33,28,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,28,28,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,11,7,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,15,23,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,33,23,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,34,19,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,36,23,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,1,26,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,28,23,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,20,26,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,34,19,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,10,22,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,28,28,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,20,28,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,28,23,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,10,22,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,34,27,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,24,19,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,28,23,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,28,23,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,34,19,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,34,27,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,14,18,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,28,27,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,27,23,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,28,28,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,28,27,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,28,27,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,34,27,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,34,27,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,34,27,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,34,27,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,22,18,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,11,18,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,34,27,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,27,23,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,34,27,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,34,27,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,28,23,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,11,22,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,27,23,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,24,1,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,3,11,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,14,28,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,6,23,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,20,28,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,11,22,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,31,11,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,31,1,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,28,28,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,28,23,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,22,23,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,27,23,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,28,25,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,18,18,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,18,23,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,28,23,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,6,19,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,19,28,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,20,19,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,30,19,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,17,17,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,15,22,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,20,13,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,22,13,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,33,14,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,20,13,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,17,11,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,14,1,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,20,26,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,14,13,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,11,6,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,17,8,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,20,28,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,28,23,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,7,14,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,3,13,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,28,23,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,28,11,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,22,13,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,28,11,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,28,11,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,3,13,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,7,14,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,28,28,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,33,14,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,28,28,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,15,28,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,28,23,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,14,28,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,24,13,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,14,23,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,28,28,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,20,28,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,3,13,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,36,23,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,15,23,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,24,14,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,15,28,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,33,28,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,20,19,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,11,19,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,14,12,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,23,19,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,11,13,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,1,7,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,2,0,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,14,28,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,14,28,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,3,18,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,28,19,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,27,7,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,14,28,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,3,12,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,11,13,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,7,0,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,18,0,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,23,0,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,31,0,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,3,11,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,36,13,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,10,22,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,24,19,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,10,22,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,24,10,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,15,23,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,24,10,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,3,11,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,14,23,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,24,10,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,36,13,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,1,13,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,36,23,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,36,13,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,23,22,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,3,11,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,32,28,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,28,28,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,14,19,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,36,1,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,34,5,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,34,26,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,18,26,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,22,18,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,14,25,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,18,1,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,18,1,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,30,25,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,10,22,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,11,26,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,3,26,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,11,19,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,11,19,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,20,0,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,11,19,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,30,19,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,11,23,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,9,18,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,26,13,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,26,14,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,20,28,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,11,23,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,33,23,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,21,11,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,22,23,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,36,13,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,33,25,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,1,23,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,36,23,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,1,19,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,10,8,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,27,6,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,3,11,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,3,23,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,11,19,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,5,0,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,24,9,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,15,28,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,8,0,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,19,0,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,3,13,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,24,9,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,3,23,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,20,28,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,5,26,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,36,28,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,5,0,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,15,28,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,15,7,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,3,13,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,11,24,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,1,26,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,11,26,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,11,22,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,36,0,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,33,0,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,22,1,12/10/2016,179,26,30,265.017,19,3,0,0,8
296,34,7,12/10/2016,118,10,37,265.017,28,1,0,0,3
297,13,22,12/10/2016,369,17,31,265.017,25,1,3,0,8
298,3,28,14/10/2016,179,51,38,265.017,31,1,0,0,1
299,22,1,14/10/2016,179,26,30,265.017,19,3,0,0,64
300,5,0,14/10/2016,235,20,43,265.017,38,1,1,0,0
301,11,19,15/10/2016,289,36,33,265.017,30,1,2,1,16
302,20,28,16/10/2016,260,50,36,265.017,23,1,4,0,3
303,5,0,16/10/2016,235,20,43,265.017,38,1,1,0,0
304,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
305,5,23,19/10/2016,235,20,43,265.017,38,1,1,0,2
306,36,28,20/10/2016,118,13,50,265.017,31,1,1,0,1
307,15,28,20/10/2016,291,31,40,265.017,25,1,1,1,4
308,22,23,22/10/2016,179,26,30,265.017,19,3,0,0,16
309,36,28,22/10/2016,118,13,50,265.017,31,1,1,0,1
310,10,10,26/10/2016,361,52,28,265.017,27,1,1,4,8
311,20,0,27/10/2016,260,50,36,265.017,23,1,4,0,0
312,15,0,27/10/2016,291,31,40,265.017,25,1,1,1,0
313,30,0,27/10/2016,157,27,29,265.017,22,1,0,0,0
314,22,1,28/10/2016,179,26,30,265.017,19,3,0,0,5
315,22,7,28/10/2016,179,26,30,265.017,19,3,0,0,5
316,36,23,29/10/2016,118,13,50,265.017,31,1,1,0,1
317,34,11,07/11/2016,118,10,37,284.031,28,1,0,0,8
318,33,23,07/11/2016,248,25,47,284.031,32,1,2,1,2
319,3,6,08/11/2016,179,51,38,284.031,31,1,0,0,8
320,20,28,11/11/2016,260,50,36,284.031,23,1,4,0,3
321,15,23,14/11/2016,291,31,40,284.031,25,1,1,1,1
322,23,1,14/11/2016,378,49,36,284.031,21,1,2,4,8
323,14,11,14/11/2016,155,12,34,284.031,25,1,2,0,120
324,5,26,14/11/2016,235,20,43,284.031,38,1,1,0,8
325,18,0,15/11/2016,330,16,28,284.031,25,2,0,0,0
326,1,18,16/11/2016,235,11,37,284.031,29,3,1,1,1
327,34,11,16/11/2016,118,10,37,284.031,28,1,0,0,3
328,1,25,17/11/2016,235,11,37,284.031,29,3,1,1,2
329,3,28,17/11/2016,179,51,38,284.031,31,1,0,0,3
330,24,13,18/11/2016,246,25,41,284.031,23,1,0,0,8
331,15,12,18/11/2016,291,31,40,284.031,25,1,1,1,4
332,24,13,21/11/2016,246,25,41,284.031,23,1,0,0,8
333,3,28,22/11/2016,179,51,38,284.031,31,1,0,0,1
334,20,10,23/11/2016,260,50,36,284.031,23,1,4,0,8
335,20,15,25/11/2016,260,50,36,284.031,23,1,4,0,8
336,23,0,25/11/2016,378,49,36,284.031,21,1,2,4,0
337,7,0,29/11/2016,279,5,39,284.031,24,1,2,0,0
338,3,23,24/11/2016,179,51,38,284.031,31,1,0,0,1
339,28,12,05/12/2016,225,26,28,236.629,24,1,1,2,3
340,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,2
341,3,28,05/12/2016,179,51,38,236.629,31,1,0,0,1
342,1,23,05/12/2016,235,11,37,236.629,29,3,1,1,3
343,36,28,06/12/2016,118,13,50,236.629,31,1,1,0,1
344,20,28,09/12/2016,260,50,36,236.629,23,1,4,0,4
345,24,4,15/12/2016,246,25,41,236.629,23,1,0,0,8
346,3,28,15/12/2016,179,51,38,236.629,31,1,0,0,1
347,3,28,16/12/2016,179,51,38,236.629,31,1,0,0,1
348,22,23,20/12/2016,179,26,30,236.629,19,3,0,0,1
349,34,25,20/12/2016,118,10,37,236.629,28,1,0,0,8
350,1,25,22/12/2016,235,11,37,236.629,29,3,1,1,2
351,3,28,23/12/2016,179,51,38,236.629,31,1,0,0,1
352,5,13,20/12/2016,235,20,43,236.629,38,1,1,0,8
353,1,14,20/12/2016,235,11,37,236.629,29,3,1,1,4
354,20,26,21/12/2016,260,50,36,236.629,23,1,4,0,8
355,30,28,19/12/2016,157,27,29,236.629,22,1,0,0,2
356,3,28,19/12/2016,179,51,38,236.629,31,1,0,0,3
357,11,19,19/12/2016,289,36,33,236.629,30,1,2,1,8
358,28,23,04/01/2017,225,26,28,330.061,24,1,1,2,5
359,34,19,09/01/2017,118,10,37,330.061,28,1,0,0,32
360,14,23,09/01/2017,155,12,34,330.061,25,1,2,0,2
361,1,13,03/01/2017,235,11,37,330.061,29,3,1,1,1
362,14,23,03/01/2017,155,12,34,330.061,25,1,2,0,4
363,11,26,09/01/2017,289,36,33,330.061,30,1,2,1,8
364,15,3,11/01/2017,291,31,40,330.061,25,1,1,1,8
365,5,26,16/01/2017,235,20,43,330.061,38,1,1,0,8
366,36,26,16/01/2017,118,13,50,330.061,31,1,1,0,4
367,3,28,25/01/2017,179,51,38,330.061,31,1,0,0,1
368,3,28,27/01/2017,179,51,38,330.061,31,1,0,0,1
369,34,28,07/02/2017,118,10,37,251.818,28,1,0,0,2
370,3,27,01/02/2017,179,51,38,251.818,31,1,0,0,3
371,28,7,01/02/2017,225,26,28,251.818,24,1,1,2,1
372,11,22,03/02/2017,289,36,33,251.818,30,1,2,1,3
373,20,28,10/02/2017,260,50,36,251.818,23,1,4,0,3
374,3,23,17/02/2017,179,51,38,251.818,31,1,0,0,3
375,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,2
376,3,27,15/02/2017,179,51,38,251.818,31,1,0,0,3
377,3,10,16/02/2017,179,51,38,251.818,31,1,0,0,8
378,24,26,16/02/2017,246,25,41,251.818,23,1,0,0,8
379,3,27,17/02/2017,179,51,38,251.818,31,1,0,0,3
380,6,22,13/02/2017,189,29,33,251.818,25,1,2,2,8
381,3,27,13/02/2017,179,51,38,251.818,31,1,0,0,3
382,24,23,21/02/2017,246,25,41,251.818,23,1,0,0,2
383,15,23,21/02/2017,291,31,40,251.818,25,1,1,1,2
384,30,11,22/02/2017,157,27,29,251.818,22,1,0,0,16
385,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
386,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
387,24,10,24/02/2017,246,25,41,251.818,23,1,0,0,24
388,3,27,22/02/2017,179,51,38,251.818,31,1,0,0,3
389,3,27,24/02/2017,179,51,38,251.818,31,1,0,0,3
390,34,18,07/03/2017,118,10,37,244.387,28,1,0,0,8
391,24,19,08/03/2017,246,25,41,244.387,23,1,0,0,16
392,24,28,10/03/2017,246,25,41,244.387,23,1,0,0,2
393,20,28,10/03/2017,260,50,36,244.387,23,1,4,0,4
394,3,28,13/03/2017,179,51,38,244.387,31,1,0,0,2
395,1,22,13/03/2017,235,11,37,244.387,29,3,1,1,8
396,17,22,14/03/2017,179,22,40,244.387,22,2,2,0,8
397,23,22,14/03/2017,378,49,36,244.387,21,1,2,4,8
398,3,28,20/03/2017,179,51,38,244.387,31,1,0,0,16
399,10,22,22/03/2017,361,52,28,244.387,27,1,1,4,8
400,13,0,22/03/2017,369,17,31,244.387,25,1,3,0,0

In [254]:
df.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [255]:
df = df.drop(['ID'], axis = 1)

In [256]:
df.head()

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [257]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [258]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [259]:

reason_columns = pd.get_dummies(df['Reason for Absence'])

reason_columns['check'] = reason_columns.sum(axis=1)

In [260]:
reason_columns['check']

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
30     1
31     1
32     1
33     1
34     1
35     1
36     1
37     1
38     1
39     1
40     1
41     1
42     1
43     1
44     1
45     1
46     1
47     1
48     1
49     1
50     1
51     1
52     1
53     1
54     1
55     1
56     1
57     1
58     1
59     1
60     1
61     1
62     1
63     1
64     1
65     1
66     1
67     1
68     1
69     1
70     1
71     1
72     1
73     1
74     1
75     1
76     1
77     1
78     1
79     1
80     1
81     1
82     1
83     1
84     1
85     1
86     1
87     1
88     1
89     1
90     1
91     1
92     1
93     1
94     1
95     1
96     1
97     1
98     1
99     1
100    1
101    1
102    1
103    1
104    1
105    1
106    1
107    1
108    1
109    1
110    1
111    1
112    1
113    1
114    1
115    1
116    1
117    1
118    1
119    1
120    1
121    1
122    1
123    1
124    1
125    1
126    1
127    1
128    1
129    1
130    1
131    1
132    1
133    1
134    1
135    1
136    1
137    1
138    1
139    1
140    1
141    1
142    1
143    1
144    1
145    1
146    1
147    1
148    1
149    1
150    1
151    1
152    1
153    1
154    1
155    1
156    1
157    1
158    1
159    1
160    1
161    1
162    1
163    1
164    1
165    1
166    1
167    1
168    1
169    1
170    1
171    1
172    1
173    1
174    1
175    1
176    1
177    1
178    1
179    1
180    1
181    1
182    1
183    1
184    1
185    1
186    1
187    1
188    1
189    1
190    1
191    1
192    1
193    1
194    1
195    1
196    1
197    1
198    1
199    1
200    1
201    1
202    1
203    1
204    1
205    1
206    1
207    1
208    1
209    1
210    1
211    1
212    1
213    1
214    1
215    1
216    1
217    1
218    1
219    1
220    1
221    1
222    1
223    1
224    1
225    1
226    1
227    1
228    1
229    1
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    1
239    1
240    1
241    1
242    1
243    1
244    1
245    1
246    1
247    1
248    1
249    1
250    1
251    1
252    1
253    1
254    1
255    1
256    1
257    1
258    1
259    1
260    1
261    1
262    1
263    1
264    1
265    1
266    1
267    1
268    1
269    1
270    1
271    1
272    1
273    1
274    1
275    1
276    1
277    1
278    1
279    1
280    1
281    1
282    1
283    1
284    1
285    1
286    1
287    1
288    1
289    1
290    1
291    1
292    1
293    1
294    1
295    1
296    1
297    1
298    1
299    1
300    1
301    1
302    1
303    1
304    1
305    1
306    1
307    1
308    1
309    1
310    1
311    1
312    1
313    1
314    1
315    1
316    1
317    1
318    1
319    1
320    1
321    1
322    1
323    1
324    1
325    1
326    1
327    1
328    1
329    1
330    1
331    1
332    1
333    1
334    1
335    1
336    1
337    1
338    1
339    1
340    1
341    1
342    1
343    1
344    1
345    1
346    1
347    1
348    1
349    1
350    1
351    1
352    1
353    1
354    1
355    1
356    1
357    1
358    1
359    1
360    1
361    1
362    1
363    1
364    1
365    1
366    1
367    1
368    1
369    1
370    1
371    1
372    1
373    1
374    1
375    1
376    1
377    1
378    1
379    1
380    1
381    1
382    1
383    1
384    1
385    1
386    1
387    1
388    1
389    1
390    1
391    1
392    1
393    1
394    1
395    1
396    1
397    1
398    1
399    1
400    1
401    1
402    1
403    1
404    1
405    1
406    1
407    1
408    1
409    1
410    1
411    1
412    1
413    1
414    1
415    1
416    1
417    1
418    1
419    1
420    1
421    1
422    1
423    1
424    1
425    1
426    1
427    1
428    1
429    1
430    1
431    1
432    1
433    1
434    1
435    1
436    1
437    1
438    1
439    1
440    1
441    1
442    1
443    1
444    1
445    1
446    1
447    1
448    1
449    1
450    1
451    1
452    1
453    1
454    1
455    1
456    1
457    1
458    1
459    1
460    1
461    1
462    1
463    1
464    1
465    1
466    1
467    1
468    1
469    1
470    1
471    1
472    1
473    1
474    1
475    1
476    1
477    1
478    1
479    1
480    1
481    1
482    1
483    1
484    1
485    1
486    1
487    1
488    1
489    1
490    1
491    1
492    1
493    1
494    1
495    1
496    1
497    1
498    1
499    1
500    1
501    1
502    1
503    1
504    1
505    1
506    1
507    1
508    1
509    1
510    1
511    1
512    1
513    1
514    1
515    1
516    1
517    1
518    1
519    1
520    1
521    1
522    1
523    1
524    1
525    1
526    1
527    1
528    1
529    1
530    1
531    1
532    1
533    1
534    1
535    1
536    1
537    1
538    1
539    1
540    1
541    1
542    1
543    1
544    1
545    1
546    1
547    1
548    1
549    1
550    1
551    1
552    1
553    1
554    1
555    1
556    1
557    1
558    1
559    1
560    1
561    1
562    1
563    1
564    1
565    1
566    1
567    1
568    1
569    1
570    1
571    1
572    1
573    1
574    1
575    1
576    1
577    1
578    1
579    1
580    1
581    1
582    1
583    1
584    1
585    1
586    1
587    1
588    1
589    1
590    1
591    1
592    1
593    1
594    1
595    1
596    1
597    1
598    1
599    1
600    1
601    1
602    1
603    1
604    1
605    1
606    1
607    1
608    1
609    1
610    1
611    1
612    1
613    1
614    1
615    1
616    1
617    1
618    1
619    1
620    1
621    1
622    1
623    1
624    1
625    1
626    1
627    1
628    1
629    1
630    1
631    1
632    1
633    1
634    1
635    1
636    1
637    1
638    1
639    1
640    1
641    1
642    1
643    1
644    1
645    1
646    1
647    1
648    1
649    1
650    1
651    1
652    1
653    1
654    1
655    1
656    1
657    1
658    1
659    1
660    1
661    1
662    1
663    1
664    1
665    1
666    1
667    1
668    1
669    1
670    1
671    1
672    1
673    1
674    1
675    1
676    1
677    1
678    1
679    1
680    1
681    1
682    1
683    1
684    1
685    1
686    1
687    1
688    1
689    1
690    1
691    1
692    1
693    1
694    1
695    1
696    1
697    1
698    1
699    1
Name: check, dtype: int64

In [261]:
reason_columns['check'].sum(axis=0)

700

In [262]:
reason_columns = reason_columns.drop(['check'], axis = 1)

In [263]:
reason_columns=reason_columns.iloc[ : , 1 :]

In [264]:
reason_columns

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
51,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
53,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
55,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
56,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
58,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
62,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
67,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
68,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
69,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
72,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
73,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
74,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
75,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
76,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
77,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
78,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
82,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
84,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
85,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
87,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
89,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
91,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
92,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
93,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
95,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
96,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
106,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
107,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
109,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
111,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
112,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
113,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
114,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
115,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
116,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
117,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
118,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
119,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
120,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
121,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
122,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
124,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
126,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
127,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
129,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
130,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
132,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
133,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
134,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
135,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
138,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
140,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
141,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
142,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
143,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
144,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
145,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
147,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
148,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
149,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
152,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
153,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
154,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
155,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
156,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
157,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
158,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
159,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
160,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
161,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
162,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
163,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
164,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
165,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
166,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
167,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
168,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
169,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
170,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
171,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
172,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
173,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
174,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
175,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
176,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
177,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
178,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
179,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
180,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
181,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
182,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
183,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
184,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
185,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
186,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
187,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
188,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
189,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
190,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
191,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
192,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
193,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
194,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
196,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
197,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
198,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
199,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
201,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
202,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
203,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
204,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
205,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
206,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
207,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
208,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
209,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
210,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
211,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
212,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
213,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
214,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
215,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
217,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
218,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
219,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
220,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
221,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
222,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
223,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
224,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
225,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
226,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
227,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
228,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
229,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
230,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
231,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
232,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
233,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
234,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
235,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
236,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
237,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
238,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
239,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
240,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
241,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
242,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
243,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
244,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
245,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
246,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
247,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
248,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
249,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
250,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
251,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
252,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
253,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
254,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
256,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
257,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
258,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
259,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
260,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
261,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
262,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
263,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
264,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
265,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
266,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
267,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
268,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
269,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
270,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
271,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
272,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
273,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
274,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
275,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
276,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
277,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
278,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
279,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
280,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
281,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
282,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
283,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
284,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
286,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
287,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
288,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
289,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
290,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
291,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
292,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
293,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
294,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
295,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
296,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
297,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
298,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
299,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
301,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
302,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
303,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
304,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
305,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
306,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
307,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
308,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
309,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
310,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
311,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
312,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
313,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
314,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
315,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
316,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
317,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
318,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
319,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
320,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
321,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
322,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
323,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
324,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
325,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
326,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
327,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
328,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
329,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
330,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
331,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
332,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
333,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
334,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
335,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
336,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
337,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
338,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
339,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
340,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
341,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
342,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
343,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
344,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [265]:
reason_type_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_type_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_type_4 = reason_columns.loc[:, 22:].max(axis=1)

In [266]:
reason_type_1

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    1
140    0
141    0
142    0
143    0
144    1
145    1
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    1
161    1
162    1
163    1
164    1
165    1
166    0
167    1
168    1
169    1
170    0
171    0
172    1
173    1
174    0
175    1
176    1
177    1
178    1
179    1
180    1
181    0
182    1
183    0
184    0
185    0
186    0
187    1
188    0
189    0
190    0
191    1
192    0
193    0
194    1
195    0
196    0
197    0
198    0
199    1
200    0
201    1
202    1
203    0
204    1
205    0
206    0
207    0
208    0
209    1
210    0
211    1
212    1
213    0
214    0
215    0
216    0
217    1
218    1
219    0
220    0
221    0
222    1
223    0
224    1
225    1
226    0
227    1
228    1
229    1
230    0
231    1
232    0
233    1
234    0
235    0
236    0
237    1
238    1
239    0
240    0
241    0
242    0
243    1
244    1
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    0
253    0
254    0
255    0
256    1
257    1
258    0
259    0
260    0
261    1
262    0
263    1
264    0
265    0
266    0
267    0
268    1
269    1
270    1
271    0
272    0
273    0
274    1
275    0
276    0
277    0
278    1
279    1
280    0
281    0
282    0
283    0
284    0
285    0
286    0
287    1
288    1
289    0
290    0
291    0
292    0
293    0
294    0
295    1
296    1
297    0
298    0
299    1
300    0
301    0
302    0
303    0
304    0
305    0
306    0
307    0
308    0
309    0
310    1
311    0
312    0
313    0
314    1
315    1
316    0
317    1
318    0
319    1
320    0
321    0
322    1
323    1
324    0
325    0
326    0
327    1
328    0
329    0
330    1
331    1
332    1
333    0
334    1
335    0
336    0
337    0
338    0
339    1
340    0
341    0
342    0
343    0
344    0
345    1
346    0
347    0
348    0
349    0
350    0
351    0
352    1
353    1
354    0
355    0
356    0
357    0
358    0
359    0
360    0
361    1
362    0
363    0
364    1
365    0
366    0
367    0
368    0
369    0
370    0
371    1
372    0
373    0
374    0
375    0
376    0
377    1
378    0
379    0
380    0
381    0
382    0
383    0
384    1
385    0
386    0
387    1
388    0
389    0
390    0
391    0
392    0
393    0
394    0
395    0
396    0
397    0
398    0
399    0
400    0
401    0
402    0
403    1
404    1
405    0
406    0
407    0
408    0
409    0
410    0
411    0
412    0
413    0
414    0
415    0
416    0
417    0
418    0
419    0
420    1
421    0
422    0
423    0
424    1
425    1
426    0
427    1
428    0
429    0
430    0
431    0
432    1
433    1
434    0
435    0
436    1
437    0
438    0
439    1
440    0
441    0
442    0
443    0
444    0
445    0
446    0
447    1
448    0
449    0
450    0
451    0
452    0
453    0
454    0
455    1
456    0
457    0
458    1
459    1
460    0
461    0
462    1
463    1
464    0
465    0
466    0
467    0
468    0
469    0
470    0
471    1
472    0
473    0
474    0
475    0
476    0
477    0
478    0
479    0
480    0
481    0
482    0
483    0
484    0
485    0
486    0
487    0
488    0
489    0
490    0
491    0
492    0
493    0
494    0
495    0
496    0
497    0
498    0
499    0
500    0
501    0
502    0
503    0
504    0
505    0
506    0
507    1
508    1
509    0
510    1
511    0
512    0
513    0
514    0
515    0
516    0
517    0
518    0
519    0
520    0
521    1
522    0
523    1
524    1
525    1
526    1
527    0
528    1
529    1
530    0
531    1
532    0
533    0
534    1
535    0
536    1
537    0
538    1
539    0
540    0
541    0
542    1
543    1
544    0
545    0
546    1
547    0
548    0
549    0
550    1
551    0
552    0
553    0
554    0
555    1
556    0
557    0
558    1
559    0
560    0
561    1
562    0
563    0
564    0
565    1
566    0
567    0
568    0
569    0
570    1
571    1
572    0
573    0
574    1
575    0
576    1
577    0
578    0
579    0
580    0
581    0
582    1
583    0
584    0
585    1
586    0
587    1
588    0
589    0
590    0
591    0
592    0
593    0
594    0
595    0
596    1
597    0
598    0
599    0
600    1
601    0
602    0
603    1
604    0
605    0
606    1
607    0
608    0
609    0
610    0
611    1
612    0
613    0
614    0
615    0
616    0
617    0
618    0
619    0
620    0
621    0
622    1
623    0
624    0
625    0
626    0
627    0
628    0
629    0
630    1
631    0
632    0
633    0
634    1
635    1
636    0
637    1
638    0
639    0
640    0
641    0
642    0
643    0
644    0
645    0
646    0
647    0
648    1
649    0
650    0
651    1
652    0
653    0
654    1
655    1
656    0
657    0
658    1
659    0
660    1
661    0
662    0
663    0
664    1
665    0
666    0
667    0
668    0
669    0
670    0
671    0
672    1
673    0
674    0
675    0
676    0
677    1
678    0
679    1
680    0
681    1
682    0
683    0
684    0
685    0
686    1
687    0
688    0
689    0
690    0
691    0
692    1
693    1
694    0
695    1
696    1
697    1
698    0
699    0
dtype: uint8

In [267]:
df = df.drop(['Reason for Absence'], axis = 1)

In [268]:
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [269]:
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

In [270]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       700 non-null    object
 1   Transportation Expense     700 non-null    int64
 2   Distance to Work           700 non-null    int64
 3   Age                        700 non-null    int64
 4   Daily Work Load Average    700 non-null    float64
 5   Body Mass Index            700 non-null    int64
 6   Education                  700 non-null    int64
 7   Children                   700 non-null    int64
 8   Pets                       700 non-null    int64
 9   Absenteeism Time in Hours  700 non-null    int64
 10  0                          700 non-null    uint8
 11  1                          700 non-null    uint8
 12  2                          700 non-null    uint8
 13  3                          700 non-null    uint8
dtypes: float64(1), int64(8), object(1), uint8(4)
memory usage: 57.5+ KB

In [271]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [272]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

df.columns = column_names

In [273]:
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason_1,Reason_2,Reason_3,Reason_4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,0,0,0,1
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,0,0,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,0,0,0,1
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,1,0,0,0
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,0,0,0,1

In [274]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 
                          'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

df = df[column_names_reordered]
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [275]:
df_reason_mod = df.copy()
df_reason_mod

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2
5,0,0,0,1,10/07/2015,179,51,38,239.554,31,1,0,0,2
6,0,0,0,1,17/07/2015,361,52,28,239.554,27,1,1,4,8
7,0,0,0,1,24/07/2015,260,50,36,239.554,23,1,4,0,4
8,0,0,1,0,06/07/2015,155,12,34,239.554,25,1,2,0,40
9,0,0,0,1,13/07/2015,235,11,37,239.554,29,3,1,1,8
10,1,0,0,0,20/07/2015,260,50,36,239.554,23,1,4,0,8
11,1,0,0,0,14/07/2015,260,50,36,239.554,23,1,4,0,8
12,1,0,0,0,15/07/2015,260,50,36,239.554,23,1,4,0,8
13,1,0,0,0,15/07/2015,179,51,38,239.554,31,1,0,0,1
14,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,4
15,1,0,0,0,17/07/2015,246,25,41,239.554,23,1,0,0,8
16,0,0,0,1,17/07/2015,179,51,38,239.554,31,1,0,0,2
17,0,0,1,0,27/07/2015,179,51,38,239.554,31,1,0,0,8
18,1,0,0,0,30/07/2015,189,29,33,239.554,25,1,2,2,8
19,0,0,0,1,05/08/2015,248,25,47,205.917,32,1,2,1,2
20,1,0,0,0,12/08/2015,330,16,28,205.917,25,2,0,0,8
21,1,0,0,0,03/08/2015,179,51,38,205.917,31,1,0,0,1
22,1,0,0,0,10/08/2015,361,52,28,205.917,27,1,1,4,40
23,0,0,0,1,14/08/2015,260,50,36,205.917,23,1,4,0,4
24,0,0,1,0,17/08/2015,289,36,33,205.917,30,1,2,1,8
25,0,0,0,1,24/08/2015,361,52,28,205.917,27,1,1,4,7
26,0,0,0,1,04/08/2015,289,36,33,205.917,30,1,2,1,1
27,0,0,0,1,12/08/2015,157,27,29,205.917,22,1,0,0,4
28,0,0,1,0,19/08/2015,289,36,33,205.917,30,1,2,1,8
29,0,0,0,1,28/08/2015,179,51,38,205.917,31,1,0,0,2
30,0,0,1,0,17/08/2015,179,51,38,205.917,31,1,0,0,8
31,0,0,1,0,27/08/2015,235,29,48,205.917,33,1,1,5,8
32,0,0,0,1,27/08/2015,235,11,37,205.917,29,3,1,1,4
33,0,0,1,0,17/08/2015,235,29,48,205.917,33,1,1,5,8
34,0,0,0,1,17/08/2015,179,51,38,205.917,31,1,0,0,2
35,0,0,0,1,17/08/2015,361,52,28,205.917,27,1,1,4,1
36,0,0,0,1,04/08/2015,289,36,33,205.917,30,1,2,1,8
37,1,0,0,0,20/08/2015,291,50,32,205.917,23,1,0,0,4
38,0,0,0,1,21/08/2015,235,29,48,205.917,33,1,1,5,8
39,0,0,0,1,28/08/2015,260,50,36,205.917,23,1,4,0,4
40,0,0,0,1,01/09/2015,184,42,27,241.476,21,1,0,0,2
41,0,0,0,1,07/09/2015,118,10,37,241.476,28,1,0,0,4
42,0,0,0,1,01/09/2015,179,51,38,241.476,31,1,0,0,4
43,0,0,1,0,08/09/2015,235,20,43,241.476,38,1,1,0,8
44,0,0,0,1,09/09/2015,155,12,34,241.476,25,1,2,0,2
45,0,0,0,1,13/09/2015,118,10,37,241.476,28,1,0,0,3
46,0,0,0,1,14/09/2015,179,51,38,241.476,31,1,0,0,3
47,0,0,0,1,24/09/2015,291,31,40,241.476,25,1,1,1,4
48,0,0,0,1,04/09/2015,260,50,36,241.476,23,1,4,0,8
49,1,0,0,0,14/09/2015,291,31,40,241.476,25,1,1,1,32
50,0,0,0,0,21/09/2015,260,50,36,241.476,23,1,4,0,0
51,0,0,0,0,28/09/2015,225,26,28,241.476,24,1,1,2,0
52,0,0,0,1,08/09/2015,225,26,28,241.476,24,1,1,2,2
53,0,0,0,1,15/09/2015,118,10,37,241.476,28,1,0,0,2
54,0,0,0,0,22/09/2015,289,36,33,241.476,30,1,2,1,0
55,0,0,0,0,29/09/2015,118,13,50,241.476,31,1,1,0,0
56,0,0,1,0,16/09/2015,225,26,28,241.476,24,1,1,2,3
57,0,0,0,1,23/09/2015,179,51,38,241.476,31,1,0,0,3
58,0,0,0,0,30/09/2015,369,17,31,241.476,25,1,3,0,0
59,0,0,0,1,11/09/2015,248,25,47,241.476,32,1,2,1,1
60,0,0,0,1,18/09/2015,179,51,38,241.476,31,1,0,0,3
61,0,0,0,1,25/09/2015,260,50,36,241.476,23,1,4,0,4
62,0,0,0,1,06/10/2015,179,51,38,253.465,31,1,0,0,3
63,0,0,0,1,13/10/2015,118,10,37,253.465,28,1,0,0,3
64,0,0,0,0,14/10/2015,118,13,50,253.465,31,1,1,0,0
65,0,0,0,1,15/10/2015,179,26,30,253.465,19,3,0,0,1
66,0,0,0,1,16/10/2015,179,51,38,253.465,31,1,0,0,3
67,0,0,0,1,16/10/2015,225,26,28,253.465,24,1,1,2,3
68,0,0,0,1,06/10/2015,118,10,37,253.465,28,1,0,0,3
69,0,0,0,1,14/10/2015,225,26,28,253.465,24,1,1,2,2
70,0,0,0,1,21/10/2015,248,25,47,253.465,32,1,2,1,2
71,0,0,0,1,22/10/2015,291,31,40,253.465,25,1,1,1,5
72,0,0,0,1,21/10/2015,179,51,38,253.465,31,1,0,0,8
73,0,0,0,1,21/10/2015,225,26,28,253.465,24,1,1,2,3
74,0,0,1,0,22/10/2015,260,50,36,253.465,23,1,4,0,16
75,1,0,0,0,13/10/2015,291,31,40,253.465,25,1,1,1,8
76,0,0,0,1,20/10/2015,225,26,28,253.465,24,1,1,2,2
77,0,0,0,1,21/10/2015,289,36,33,253.465,30,1,2,1,8
78,0,0,0,1,23/10/2015,361,52,28,253.465,27,1,1,4,1
79,0,0,0,1,30/10/2015,260,50,36,253.465,23,1,4,0,3
80,0,0,0,1,05/11/2015,179,51,38,306.345,31,1,0,0,1
81,0,0,0,1,04/11/2015,225,26,28,306.345,24,1,1,2,1
82,1,0,0,0,05/11/2015,179,51,38,306.345,31,1,0,0,8
83,0,0,1,0,12/11/2015,179,22,40,306.345,22,2,2,0,8
84,0,0,0,1,19/11/2015,291,31,40,306.345,25,1,1,1,5
85,1,0,0,0,02/11/2015,155,12,34,306.345,25,1,2,0,32
86,0,0,0,1,09/11/2015,189,29,33,306.345,25,1,2,2,8
87,1,0,0,0,16/11/2015,291,31,40,306.345,25,1,1,1,40
88,0,0,0,1,18/11/2015,225,26,28,306.345,24,1,1,2,1
89,1,0,0,0,20/11/2015,155,12,34,306.345,25,1,2,0,8
90,0,0,0,1,18/11/2015,225,26,28,306.345,24,1,1,2,3
91,0,0,1,0,25/11/2015,179,22,40,306.345,22,2,2,0,8
92,1,0,0,0,20/11/2015,225,26,28,306.345,24,1,1,2,3
93,0,0,0,1,27/11/2015,260,50,36,306.345,23,1,4,0,4
94,0,0,0,1,02/11/2015,248,25,47,306.345,32,1,2,1,1
95,0,0,0,1,10/11/2015,225,26,28,306.345,24,1,1,2,3
96,1,0,0,0,11/11/2015,289,36,33,306.345,30,1,2,1,24
97,0,0,0,1,26/11/2015,291,31,40,306.345,25,1,1,1,3
98,0,0,0,1,01/12/2015,248,25,47,261.306,32,1,2,1,1
99,0,0,1,0,01/12/2015,118,10,37,261.306,28,1,0,0,64
100,0,0,0,1,02/12/2015,118,13,50,261.306,31,1,1,0,2
101,0,0,0,1,02/12/2015,235,11,37,261.306,29,3,1,1,8
102,0,0,0,1,03/12/2015,225,26,28,261.306,24,1,1,2,2
103,0,0,0,1,04/12/2015,260,50,36,261.306,23,1,4,0,8
104,0,0,1,0,08/12/2015,118,10,37,261.306,28,1,0,0,56
105,0,0,0,1,09/12/2015,361,52,28,261.306,27,1,1,4,8
106,0,0,0,1,10/12/2015,225,26,28,261.306,24,1,1,2,3
107,0,0,0,1,11/12/2015,260,50,36,261.306,23,1,4,0,3
108,0,0,0,1,15/12/2015,225,26,28,261.306,24,1,1,2,2
109,0,0,0,1,16/12/2015,361,52,28,261.306,27,1,1,4,8
110,0,0,0,1,11/12/2015,118,10,37,261.306,28,1,0,0,2
111,0,0,1,0,18/12/2015,246,25,41,261.306,23,1,0,0,8
112,0,0,0,1,18/12/2015,225,26,28,261.306,24,1,1,2,2
113,0,0,0,1,06/01/2016,225,26,28,308.593,24,1,1,2,1
114,0,0,1,0,04/01/2016,118,10,37,308.593,28,1,0,0,1
115,0,0,0,1,05/01/2016,118,10,37,308.593,28,1,0,0,1
116,0,0,1,0,05/01/2016,155,12,34,308.593,25,1,2,0,8
117,0,0,0,1,06/01/2016,225,26,28,308.593,24,1,1,2,2
118,0,0,0,1,07/01/2016,184,42,27,308.593,21,1,0,0,2
119,0,0,0,1,07/01/2016,225,26,28,308.593,24,1,1,2,2
120,0,0,0,1,08/01/2016,225,26,28,308.593,24,1,1,2,1
121,0,0,0,1,11/01/2016,118,10,37,308.593,28,1,0,0,2
122,0,0,0,1,12/01/2016,225,26,28,308.593,24,1,1,2,2
123,0,0,0,1,12/01/2016,118,10,37,308.593,28,1,0,0,2
124,0,0,0,1,13/01/2016,118,10,37,308.593,28,1,0,0,2
125,0,0,0,1,14/01/2016,118,10,37,308.593,28,1,0,0,2
126,0,0,0,1,15/01/2016,118,10,37,308.593,28,1,0,0,2
127,0,0,0,1,11/01/2016,118,10,37,308.593,28,1,0,0,2
128,0,0,0,1,12/01/2016,118,10,37,308.593,28,1,0,0,2
129,0,0,1,0,12/01/2016,179,26,30,308.593,19,3,0,0,8
130,0,0,1,0,12/01/2016,289,36,33,308.593,30,1,2,1,8
131,0,0,0,1,13/01/2016,118,10,37,308.593,28,1,0,0,2
132,0,0,0,1,21/01/2016,184,42,27,308.593,21,1,0,0,2
133,0,0,0,1,28/01/2016,118,10,37,308.593,28,1,0,0,2
134,0,0,0,1,25/01/2016,118,10,37,308.593,28,1,0,0,0
135,0,0,0,1,26/01/2016,225,26,28,308.593,24,1,1,2,1
136,0,0,0,1,28/01/2016,289,36,33,308.593,30,1,2,1,3
137,0,0,0,1,05/02/2016,184,42,27,302.585,21,1,0,0,1
138,1,0,0,0,03/02/2016,246,25,41,302.585,23,1,0,0,8
139,1,0,0,0,10/02/2016,179,51,38,302.585,31,1,0,0,8
140,0,0,0,1,11/02/2016,155,12,34,302.585,25,1,2,0,2
141,0,0,0,1,11/02/2016,189,29,33,302.585,25,1,2,2,8
142,0,0,0,1,12/02/2016,260,50,36,302.585,23,1,4,0,2
143,0,0,0,1,12/02/2016,289,36,33,302.585,30,1,2,1,8
144,1,0,0,0,08/02/2016,388,15,50,302.585,24,1,0,0,8
145,1,0,0,0,09/02/2016,388,15,50,302.585,24,1,0,0,8
146,0,0,0,1,15/02/2016,225,26,28,302.585,24,1,1,2,2
147,0,0,0,1,09/02/2016,225,26,28,302.585,24,1,1,2,2
148,0,0,0,1,16/02/2016,179,26,30,302.585,19,3,0,0,1
149,0,0,0,1,23/02/2016,184,42,27,302.585,21,1,0,0,8
150,0,0,0,1,25/02/2016,225,26,28,302.585,24,1,1,2,3
151,0,0,1,0,15/02/2016,330,16,28,302.585,25,2,0,0,8
152,0,0,0,1,16/02/2016,330,16,28,302.585,25,2,0,0,1
153,0,0,0,1,17/02/2016,225,26,28,302.585,24,1,1,2,1
154,0,0,1,0,25/02/2016,189,29,33,302.585,25,1,2,2,8
155,0,0,0,1,01/03/2016,291,50,32,343.253,23,1,0,0,2
156,0,0,1,0,01/03/2016,260,50,36,343.253,23,1,4,0,8
157,0,0,1,0,08/03/2016,157,27,29,343.253,22,1,0,0,3
158,0,1,0,0,15/03/2016,179,22,40,343.253,22,2,2,0,8
159,0,0,0,1,16/03/2016,291,31,40,343.253,25,1,1,1,8
160,1,0,0,0,02/03/2016,260,50,36,343.253,23,1,4,0,8
161,1,0,0,0,03/03/2016,179,26,30,343.253,19,3,0,0,8
162,1,0,0,0,04/03/2016,248,25,47,343.253,32,1,2,1,3
163,1,0,0,0,04/03/2016,260,50,36,343.253,23,1,4,0,40
164,1,0,0,0,07/03/2016,179,22,40,343.253,22,2,2,0,40
165,1,0,0,0,14/03/2016,155,12,34,343.253,25,1,2,0,16
166,0,0,0,1,21/03/2016,260,50,36,343.253,23,1,4,0,16
167,1,0,0,0,22/03/2016,155,12,34,343.253,25,1,2,0,8
168,1,0,0,0,24/03/2016,289,36,33,343.253,30,1,2,1,8
169,1,0,0,0,24/03/2016,179,22,40,343.253,22,2,2,0,8
170,0,0,0,1,25/03/2016,260,50,36,343.253,23,1,4,0,4
171,0,0,0,1,25/03/2016,225,26,28,343.253,24,1,1,2,1
172,1,0,0,0,28/03/2016,279,5,39,343.253,24,1,2,0,8
173,1,0,0,0,29/03/2016,179,51,38,343.253,31,1,0,0,24
174,0,0,0,1,30/03/2016,225,26,28,343.253,24,1,1,2,2
175,1,0,0,0,28/03/2016,225,26,28,343.253,24,1,1,2,8
176,1,0,0,0,28/03/2016,179,26,30,343.253,19,3,0,0,1
177,1,0,0,0,29/03/2016,225,26,28,343.253,24,1,1,2,8
178,1,0,0,0,30/03/2016,225,26,28,343.253,24,1,1,2,16
179,1,0,0,0,30/03/2016,179,51,38,343.253,31,1,0,0,3
180,1,0,0,0,17/03/2016,279,5,39,343.253,24,1,2,0,16
181,0,0,0,1,18/03/2016,225,26,28,343.253,24,1,1,2,2
182,1,0,0,0,25/03/2016,248,25,47,343.253,32,1,2,1,3
183,0,0,0,1,28/03/2016,225,26,28,343.253,24,1,1,2,1
184,0,0,0,1,06/04/2016,291,31,40,326.452,25,1,1,1,1
185,0,0,0,1,13/04/2016,225,26,28,326.452,24,1,1,2,1
186,0,0,0,1,12/04/2016,155,12,34,326.452,25,1,2,0,1
187,1,0,0,0,13/04/2016,246,25,41,326.452,23,1,0,0,24
188,0,0,0,1,14/04/2016,155,12,34,326.452,25,1,2,0,1
189,0,0,0,1,15/04/2016,225,26,28,326.452,24,1,1,2,2
190,0,0,0,1,15/04/2016,260,50,36,326.452,23,1,4,0,4
191,1,0,0,0,06/04/2016,179,51,38,326.452,31,1,0,0,24
192,0,0,0,1,07/04/2016,118,13,50,326.452,31,1,1,0,1
193,0,0,0,1,08/04/2016,291,31,40,326.452,25,1,1,1,3
194,1,0,0,0,08/04/2016,246,25,41,326.452,23,1,0,0,8
195,0,0,0,1,22/04/2016,291,31,40,326.452,25,1,1,1,1
196,0,0,0,1,29/04/2016,248,25,47,326.452,32,1,2,1,8
197,0,0,1,0,29/04/2016,260,50,36,326.452,23,1,4,0,56
198,0,0,1,0,26/04/2016,289,36,33,326.452,30,1,2,1,8
199,1,0,0,0,27/04/2016,155,12,34,326.452,25,1,2,0,24
200,0,0,1,0,27/04/2016,378,49,36,326.452,21,1,2,4,8
201,1,0,0,0,28/04/2016,289,36,33,326.452,30,1,2,1,16
202,1,0,0,0,08/04/2016,235,11,37,326.452,29,3,1,1,3
203,0,0,0,0,04/04/2016,235,29,48,326.452,33,1,1,5,0
204,1,0,0,0,04/05/2016,289,36,33,378.884,30,1,2,1,8
205,0,0,0,1,05/05/2016,155,12,34,378.884,25,1,2,0,2
206,0,0,0,1,02/05/2016,155,12,34,378.884,25,1,2,0,1
207,0,0,1,0,03/05/2016,179,51,38,378.884,31,1,0,0,8
208,0,0,1,0,03/05/2016,225,26,28,378.884,24,1,1,2,8
209,1,0,0,0,11/05/2016,184,42,27,378.884,21,1,0,0,4
210,0,0,0,1,09/05/2016,155,12,34,378.884,25,1,2,0,2
211,1,0,0,0,10/05/2016,179,51,38,378.884,31,1,0,0,1
212,1,0,0,0,04/05/2016,289,36,33,378.884,30,1,2,1,24
213,0,0,0,0,11/05/2016,279,5,39,378.884,24,1,2,0,0
214,0,0,0,0,18/05/2016,330,16,28,378.884,25,2,0,0,0
215,0,0,0,0,25/05/2016,378,49,36,378.884,21,1,2,4,0
216,0,0,0,0,25/05/2016,388,15,50,378.884,24,1,0,0,0
217,1,0,0,0,24/05/2016,179,51,38,378.884,31,1,0,0,1
218,1,0,0,0,11/05/2016,118,13,50,378.884,31,1,1,0,24
219,0,0,0,1,27/05/2016,361,52,28,378.884,27,1,1,4,8
220,0,0,1,0,06/06/2016,246,25,41,377.550,23,1,0,0,8
221,0,0,0,1,13/06/2016,361,52,28,377.550,27,1,1,4,8
222,1,0,0,0,14/06/2016,246,25,41,377.550,23,1,0,0,24
223,0,0,0,1,16/06/2016,291,31,40,377.550,25,1,1,1,4
224,1,0,0,0,17/06/2016,246,25,41,377.550,23,1,0,0,8
225,1,0,0,0,13/06/2016,179,51,38,377.550,31,1,0,0,8
226,0,0,0,1,20/06/2016,155,12,34,377.550,25,1,2,0,4
227,1,0,0,0,27/06/2016,246,25,41,377.550,23,1,0,0,8
228,1,0,0,0,29/06/2016,118,13,50,377.550,31,1,1,0,8
229,1,0,0,0,03/06/2016,235,11,37,377.550,29,3,1,1,16
230,0,0,0,1,07/06/2016,118,13,50,377.550,31,1,1,0,1
231,1,0,0,0,08/06/2016,118,13,50,377.550,31,1,1,0,80
232,0,0,0,1,09/06/2016,378,49,36,377.550,21,1,2,4,8
233,1,0,0,0,10/06/2016,179,51,38,377.550,31,1,0,0,2
234,0,0,0,1,20/06/2016,289,48,49,377.550,36,1,0,2,2
235,0,0,0,1,30/06/2016,225,26,28,377.550,24,1,1,2,2
236,0,0,1,0,05/07/2016,155,12,34,275.312,25,1,2,0,16
237,1,0,0,0,06/07/2016,118,13,50,275.312,31,1,1,0,8
238,1,0,0,0,08/07/2016,118,10,37,275.312,28,1,0,0,8
239,0,0,0,1,08/07/2016,118,10,37,275.312,28,1,0,0,4
240,0,0,0,1,12/07/2016,330,16,28,275.312,25,2,0,0,8
241,0,0,1,0,14/07/2016,179,26,30,275.312,19,3,0,0,8
242,0,0,0,1,15/07/2016,155,12,34,275.312,25,1,2,0,2
243,1,0,0,0,18/07/2016,330,16,28,275.312,25,2,0,0,8
244,1,0,0,0,19/07/2016,330,16,28,275.312,25,2,0,0,8
245,0,0,0,1,18/07/2016,157,27,29,275.312,22,1,0,0,3
246,0,0,0,1,19/07/2016,361,52,28,275.312,27,1,1,4,8
247,0,0,0,1,20/07/2016,289,36,33,275.312,30,1,2,1,8
248,0,0,0,1,21/07/2016,179,51,38,275.312,31,1,0,0,8
249,0,0,1,0,11/07/2016,289,36,33,275.312,30,1,2,1,32
250,0,0,1,0,14/07/2016,289,36,33,275.312,30,1,2,1,8
251,0,0,0,0,21/07/2016,260,50,36,275.312,23,1,4,0,0
252,0,0,1,0,04/08/2016,289,36,33,265.615,30,1,2,1,8
253,0,0,1,0,11/08/2016,157,27,29,265.615,22,1,0,0,3
254,0,0,0,1,07/08/2016,289,36,33,265.615,30,1,2,1,1
255,0,0,1,0,08/08/2016,228,14,58,265.615,22,1,2,1,8
256,1,0,0,0,10/08/2016,300,26,43,265.615,25,1,2,1,1
257,1,0,0,0,10/08/2016,300,26,43,265.615,25,1,2,1,2
258,0,0,0,1,11/08/2016,260,50,36,265.615,23,1,4,0,4
259,0,0,0,1,08/08/2016,289,36,33,265.615,30,1,2,1,4
260,0,0,0,1,09/08/2016,248,25,47,265.615,32,1,2,1,1
261,1,0,0,0,10/08/2016,268,11,33,265.615,25,2,0,0,8
262,0,0,0,1,10/08/2016,179,26,30,265.615,19,3,0,0,1
263,1,0,0,0,10/08/2016,118,13,50,265.615,31,1,1,0,3
264,0,0,0,1,14/08/2016,248,25,47,265.615,32,1,2,1,2
265,0,0,0,1,15/08/2016,235,11,37,265.615,29,3,1,1,1
266,0,0,0,1,17/08/2016,118,13,50,265.615,31,1,1,0,1
267,0,0,1,0,24/08/2016,235,11,37,265.615,29,3,1,1,8
268,1,0,0,0,08/08/2016,361,52,28,265.615,27,1,1,4,8
269,1,0,0,0,30/08/2016,184,42,27,265.615,21,1,0,0,8
270,1,0,0,0,05/09/2016,179,51,38,294.217,31,1,0,0,8
271,0,0,0,1,09/09/2016,179,51,38,294.217,31,1,0,0,3
272,0,0,1,0,07/09/2016,289,36,33,294.217,30,1,2,1,24
273,0,0,0,0,08/09/2016,235,20,43,294.217,38,1,1,0,0
274,1,0,0,0,12/09/2016,246,25,41,294.217,23,1,0,0,16
275,0,0,0,1,13/09/2016,291,31,40,294.217,25,1,1,1,3
276,0,0,0,0,13/09/2016,231,35,39,294.217,35,1,2,2,0
277,0,0,0,0,13/09/2016,291,50,32,294.217,23,1,0,0,0
278,1,0,0,0,14/09/2016,179,51,38,294.217,31,1,0,0,8
279,1,0,0,0,14/09/2016,246,25,41,294.217,23,1,0,0,32
280,0,0,0,1,15/09/2016,179,51,38,294.217,31,1,0,0,1
281,0,0,0,1,16/09/2016,291,31,40,294.217,25,1,1,1,4
282,0,0,0,1,16/09/2016,260,50,36,294.217,23,1,4,0,4
283,0,0,0,1,14/09/2016,235,20,43,294.217,38,1,1,0,8
284,0,0,0,1,15/09/2016,118,13,50,294.217,31,1,1,0,1
285,0,0,0,0,15/09/2016,235,20,43,294.217,38,1,1,0,0
286,0,0,0,1,16/09/2016,291,31,40,294.217,25,1,1,1,3
287,1,0,0,0,26/09/2016,291,31,40,294.217,25,1,1,1,40
288,1,0,0,0,26/09/2016,179,51,38,294.217,31,1,0,0,8
289,0,0,0,1,05/10/2016,289,36,33,265.017,30,1,2,1,8
290,0,0,0,1,05/10/2016,235,11,37,265.017,29,3,1,1,4
291,0,0,0,1,05/10/2016,289,36,33,265.017,30,1,2,1,8
292,0,0,0,1,06/10/2016,289,36,33,265.017,30,1,2,1,8
293,0,0,0,0,06/10/2016,118,13,50,265.017,31,1,1,0,0
294,0,0,0,0,06/10/2016,248,25,47,265.017,32,1,2,1,0
295,1,0,0,0,12/10/2016,179,26,30,265.017,19,3,0,0,8
296,1,0,0,0,12/10/2016,118,10,37,265.017,28,1,0,0,3
297,0,0,0,1,12/10/2016,369,17,31,265.017,25,1,3,0,8
298,0,0,0,1,14/10/2016,179,51,38,265.017,31,1,0,0,1
299,1,0,0,0,14/10/2016,179,26,30,265.017,19,3,0,0,64
300,0,0,0,0,14/10/2016,235,20,43,265.017,38,1,1,0,0
301,0,0,1,0,15/10/2016,289,36,33,265.017,30,1,2,1,16
302,0,0,0,1,16/10/2016,260,50,36,265.017,23,1,4,0,3
303,0,0,0,0,16/10/2016,235,20,43,265.017,38,1,1,0,0
304,0,0,0,1,19/10/2016,235,20,43,265.017,38,1,1,0,2
305,0,0,0,1,19/10/2016,235,20,43,265.017,38,1,1,0,2
306,0,0,0,1,20/10/2016,118,13,50,265.017,31,1,1,0,1
307,0,0,0,1,20/10/2016,291,31,40,265.017,25,1,1,1,4
308,0,0,0,1,22/10/2016,179,26,30,265.017,19,3,0,0,16
309,0,0,0,1,22/10/2016,118,13,50,265.017,31,1,1,0,1
310,1,0,0,0,26/10/2016,361,52,28,265.017,27,1,1,4,8
311,0,0,0,0,27/10/2016,260,50,36,265.017,23,1,4,0,0
312,0,0,0,0,27/10/2016,291,31,40,265.017,25,1,1,1,0
313,0,0,0,0,27/10/2016,157,27,29,265.017,22,1,0,0,0
314,1,0,0,0,28/10/2016,179,26,30,265.017,19,3,0,0,5
315,1,0,0,0,28/10/2016,179,26,30,265.017,19,3,0,0,5
316,0,0,0,1,29/10/2016,118,13,50,265.017,31,1,1,0,1
317,1,0,0,0,07/11/2016,118,10,37,284.031,28,1,0,0,8
318,0,0,0,1,07/11/2016,248,25,47,284.031,32,1,2,1,2
319,1,0,0,0,08/11/2016,179,51,38,284.031,31,1,0,0,8
320,0,0,0,1,11/11/2016,260,50,36,284.031,23,1,4,0,3
321,0,0,0,1,14/11/2016,291,31,40,284.031,25,1,1,1,1
322,1,0,0,0,14/11/2016,378,49,36,284.031,21,1,2,4,8
323,1,0,0,0,14/11/2016,155,12,34,284.031,25,1,2,0,120
324,0,0,0,1,14/11/2016,235,20,43,284.031,38,1,1,0,8
325,0,0,0,0,15/11/2016,330,16,28,284.031,25,2,0,0,0
326,0,0,1,0,16/11/2016,235,11,37,284.031,29,3,1,1,1
327,1,0,0,0,16/11/2016,118,10,37,284.031,28,1,0,0,3
328,0,0,0,1,17/11/2016,235,11,37,284.031,29,3,1,1,2
329,0,0,0,1,17/11/2016,179,51,38,284.031,31,1,0,0,3
330,1,0,0,0,18/11/2016,246,25,41,284.031,23,1,0,0,8
331,1,0,0,0,18/11/2016,291,31,40,284.031,25,1,1,1,4
332,1,0,0,0,21/11/2016,246,25,41,284.031,23,1,0,0,8
333,0,0,0,1,22/11/2016,179,51,38,284.031,31,1,0,0,1
334,1,0,0,0,23/11/2016,260,50,36,284.031,23,1,4,0,8
335,0,1,0,0,25/11/2016,260,50,36,284.031,23,1,4,0,8
336,0,0,0,0,25/11/2016,378,49,36,284.031,21,1,2,4,0
337,0,0,0,0,29/11/2016,279,5,39,284.031,24,1,2,0,0
338,0,0,0,1,24/11/2016,179,51,38,284.031,31,1,0,0,1
339,1,0,0,0,05/12/2016,225,26,28,236.629,24,1,1,2,3
340,0,0,0,1,05/12/2016,179,51,38,236.629,31,1,0,0,2
341,0,0,0,1,05/12/2016,179,51,38,236.629,31,1,0,0,1
342,0,0,0,1,05/12/2016,235,11,37,236.629,29,3,1,1,3
343,0,0,0,1,06/12/2016,118,13,50,236.629,31,1,1,0,1
344,0,0,0,1,09/12/2016,260,50,36,236.629,23,1,4,0,4
345,1,0,0,0,15/12/2016,246,25,41,236.629,23,1,0,0,8
346,0,0,0,1,15/12/2016,179,51,38,236.629,31,1,0,0,1
347,0,0,0,1,16/12/2016,179,51,38,236.629,31,1,0,0,1
348,0,0,0,1,20/12/2016,179,26,30,236.629,19,3,0,0,1
349,0,0,0,1,20/12/2016,118,10,37,236.629,28,1,0,0,8
350,0,0,0,1,22/12/2016,235,11,37,236.629,29,3,1,1,2
351,0,0,0,1,23/12/2016,179,51,38,236.629,31,1,0,0,1
352,1,0,0,0,20/12/2016,235,20,43,236.629,38,1,1,0,8
353,1,0,0,0,20/12/2016,235,11,37,236.629,29,3,1,1,4
354,0,0,0,1,21/12/2016,260,50,36,236.629,23,1,4,0,8
355,0,0,0,1,19/12/2016,157,27,29,236.629,22,1,0,0,2
356,0,0,0,1,19/12/2016,179,51,38,236.629,31,1,0,0,3
357,0,0,1,0,19/12/2016,289,36,33,236.629,30,1,2,1,8
358,0,0,0,1,04/01/2017,225,26,28,330.061,24,1,1,2,5
359,0,0,1,0,09/01/2017,118,10,37,330.061,28,1,0,0,32
360,0,0,0,1,09/01/2017,155,12,34,330.061,25,1,2,0,2
361,1,0,0,0,03/01/2017,235,11,37,330.061,29,3,1,1,1
362,0,0,0,1,03/01/2017,155,12,34,330.061,25,1,2,0,4
363,0,0,0,1,09/01/2017,289,36,33,330.061,30,1,2,1,8
364,1,0,0,0,11/01/2017,291,31,40,330.061,25,1,1,1,8
365,0,0,0,1,16/01/2017,235,20,43,330.061,38,1,1,0,8
366,0,0,0,1,16/01/2017,118,13,50,330.061,31,1,1,0,4
367,0,0,0,1,25/01/2017,179,51,38,330.061,31,1,0,0,1
368,0,0,0,1,27/01/2017,179,51,38,330.061,31,1,0,0,1
369,0,0,0,1,07/02/2017,118,10,37,251.818,28,1,0,0,2
370,0,0,0,1,01/02/2017,179,51,38,251.818,31,1,0,0,3
371,1,0,0,0,01/02/2017,225,26,28,251.818,24,1,1,2,1
372,0,0,0,1,03/02/2017,289,36,33,251.818,30,1,2,1,3
373,0,0,0,1,10/02/2017,260,50,36,251.818,23,1,4,0,3
374,0,0,0,1,17/02/2017,179,51,38,251.818,31,1,0,0,3
375,0,0,0,1,13/02/2017,179,51,38,251.818,31,1,0,0,2
376,0,0,0,1,15/02/2017,179,51,38,251.818,31,1,0,0,3
377,1,0,0,0,16/02/2017,179,51,38,251.818,31,1,0,0,8
378,0,0,0,1,16/02/2017,246,25,41,251.818,23,1,0,0,8
379,0,0,0,1,17/02/2017,179,51,38,251.818,31,1,0,0,3
380,0,0,0,1,13/02/2017,189,29,33,251.818,25,1,2,2,8
381,0,0,0,1,13/02/2017,179,51,38,251.818,31,1,0,0,3

In [276]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format = '%d/%m/%Y')

In [277]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason_1                   700 non-null    uint8
 1   Reason_2                   700 non-null    uint8
 2   Reason_3                   700 non-null    uint8
 3   Reason_4                   700 non-null    uint8
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64
 6   Distance to Work           700 non-null    int64
 7   Age                        700 non-null    int64
 8   Daily Work Load Average    700 non-null    float64
 9   Body Mass Index            700 non-null    int64
 10  Education                  700 non-null    int64
 11  Children                   700 non-null    int64
 12  Pets                       700 non-null    int64
 13  Absenteeism Time in Hours  700 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(8), uint8(4)
memory usage: 57.5 KB

In [278]:

list_months = []
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)
    
df_reason_mod['Month Value'] = list_months
df_reason_mod.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Value
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7
5,0,0,0,1,2015-07-10,179,51,38,239.554,31,1,0,0,2,7
6,0,0,0,1,2015-07-17,361,52,28,239.554,27,1,1,4,8,7
7,0,0,0,1,2015-07-24,260,50,36,239.554,23,1,4,0,4,7
8,0,0,1,0,2015-07-06,155,12,34,239.554,25,1,2,0,40,7
9,0,0,0,1,2015-07-13,235,11,37,239.554,29,3,1,1,8,7
10,1,0,0,0,2015-07-20,260,50,36,239.554,23,1,4,0,8,7
11,1,0,0,0,2015-07-14,260,50,36,239.554,23,1,4,0,8,7
12,1,0,0,0,2015-07-15,260,50,36,239.554,23,1,4,0,8,7
13,1,0,0,0,2015-07-15,179,51,38,239.554,31,1,0,0,1,7
14,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,4,7
15,1,0,0,0,2015-07-17,246,25,41,239.554,23,1,0,0,8,7
16,0,0,0,1,2015-07-17,179,51,38,239.554,31,1,0,0,2,7
17,0,0,1,0,2015-07-27,179,51,38,239.554,31,1,0,0,8,7
18,1,0,0,0,2015-07-30,189,29,33,239.554,25,1,2,2,8,7
19,0,0,0,1,2015-08-05,248,25,47,205.917,32,1,2,1,2,8

In [279]:
def date_to_weekday(date_value):
    return date_value.weekday()

df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(date_to_weekday)

df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month Value,Day of the Week
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,0,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

In [280]:
df_reason_mod = df_reason_mod.drop(['Date'], axis = 1)
column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value', 'Day of the Week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']
df_reason_mod = df_reason_mod[column_names_upd]
df_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,1,2,1,2

In [281]:
df_reason_date_mod = df_reason_mod.copy()

In [282]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4])

In [283]:
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [284]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [285]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [286]:
data_preprocessed = df_reason_date_mod.copy()
data_preprocessed.head(10)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2
5,0,0,0,1,7,4,179,51,38,239.554,31,0,0,0,2
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4,8
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0,4
8,0,0,1,0,7,0,155,12,34,239.554,25,0,2,0,40
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1,8

In [287]:
import sklearn
import numpy as np

In [288]:
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

In [289]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [290]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [291]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [292]:
data_preprocessed['Excessive Absenteeism'] = targets

In [293]:
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

In [294]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [295]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [296]:
data_with_targets is data_preprocessed

False

In [297]:
data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

In [298]:
data_with_targets.shape

(700, 12)

In [299]:
data_with_targets.iloc[:,:14]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0
5,0,0,0,1,7,179,38,31,0,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4,1
7,0,0,0,1,7,260,36,23,0,4,0,1
8,0,0,1,0,7,155,34,25,0,2,0,1
9,0,0,0,1,7,235,37,29,1,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0,1
11,1,0,0,0,7,260,36,23,0,4,0,1
12,1,0,0,0,7,260,36,23,0,4,0,1
13,1,0,0,0,7,179,38,31,0,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0,1
15,1,0,0,0,7,246,41,23,0,0,0,1
16,0,0,0,1,7,179,38,31,0,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0,1
18,1,0,0,0,7,189,33,25,0,2,2,1
19,0,0,0,1,8,248,47,32,0,2,1,0
20,1,0,0,0,8,330,28,25,1,0,0,1
21,1,0,0,0,8,179,38,31,0,0,0,0
22,1,0,0,0,8,361,28,27,0,1,4,1
23,0,0,0,1,8,260,36,23,0,4,0,1
24,0,0,1,0,8,289,33,30,0,2,1,1
25,0,0,0,1,8,361,28,27,0,1,4,1
26,0,0,0,1,8,289,33,30,0,2,1,0
27,0,0,0,1,8,157,29,22,0,0,0,1
28,0,0,1,0,8,289,33,30,0,2,1,1
29,0,0,0,1,8,179,38,31,0,0,0,0
30,0,0,1,0,8,179,38,31,0,0,0,1
31,0,0,1,0,8,235,48,33,0,1,5,1
32,0,0,0,1,8,235,37,29,1,1,1,1
33,0,0,1,0,8,235,48,33,0,1,5,1
34,0,0,0,1,8,179,38,31,0,0,0,0
35,0,0,0,1,8,361,28,27,0,1,4,0
36,0,0,0,1,8,289,33,30,0,2,1,1
37,1,0,0,0,8,291,32,23,0,0,0,1
38,0,0,0,1,8,235,48,33,0,1,5,1
39,0,0,0,1,8,260,36,23,0,4,0,1
40,0,0,0,1,9,184,27,21,0,0,0,0
41,0,0,0,1,9,118,37,28,0,0,0,1
42,0,0,0,1,9,179,38,31,0,0,0,1
43,0,0,1,0,9,235,43,38,0,1,0,1
44,0,0,0,1,9,155,34,25,0,2,0,0
45,0,0,0,1,9,118,37,28,0,0,0,0
46,0,0,0,1,9,179,38,31,0,0,0,0
47,0,0,0,1,9,291,40,25,0,1,1,1
48,0,0,0,1,9,260,36,23,0,4,0,1
49,1,0,0,0,9,291,40,25,0,1,1,1
50,0,0,0,0,9,260,36,23,0,4,0,0
51,0,0,0,0,9,225,28,24,0,1,2,0
52,0,0,0,1,9,225,28,24,0,1,2,0
53,0,0,0,1,9,118,37,28,0,0,0,0
54,0,0,0,0,9,289,33,30,0,2,1,0
55,0,0,0,0,9,118,50,31,0,1,0,0
56,0,0,1,0,9,225,28,24,0,1,2,0
57,0,0,0,1,9,179,38,31,0,0,0,0
58,0,0,0,0,9,369,31,25,0,3,0,0
59,0,0,0,1,9,248,47,32,0,2,1,0
60,0,0,0,1,9,179,38,31,0,0,0,0
61,0,0,0,1,9,260,36,23,0,4,0,1
62,0,0,0,1,10,179,38,31,0,0,0,0
63,0,0,0,1,10,118,37,28,0,0,0,0
64,0,0,0,0,10,118,50,31,0,1,0,0
65,0,0,0,1,10,179,30,19,1,0,0,0
66,0,0,0,1,10,179,38,31,0,0,0,0
67,0,0,0,1,10,225,28,24,0,1,2,0
68,0,0,0,1,10,118,37,28,0,0,0,0
69,0,0,0,1,10,225,28,24,0,1,2,0
70,0,0,0,1,10,248,47,32,0,2,1,0
71,0,0,0,1,10,291,40,25,0,1,1,1
72,0,0,0,1,10,179,38,31,0,0,0,1
73,0,0,0,1,10,225,28,24,0,1,2,0
74,0,0,1,0,10,260,36,23,0,4,0,1
75,1,0,0,0,10,291,40,25,0,1,1,1
76,0,0,0,1,10,225,28,24,0,1,2,0
77,0,0,0,1,10,289,33,30,0,2,1,1
78,0,0,0,1,10,361,28,27,0,1,4,0
79,0,0,0,1,10,260,36,23,0,4,0,0
80,0,0,0,1,11,179,38,31,0,0,0,0
81,0,0,0,1,11,225,28,24,0,1,2,0
82,1,0,0,0,11,179,38,31,0,0,0,1
83,0,0,1,0,11,179,40,22,1,2,0,1
84,0,0,0,1,11,291,40,25,0,1,1,1
85,1,0,0,0,11,155,34,25,0,2,0,1
86,0,0,0,1,11,189,33,25,0,2,2,1
87,1,0,0,0,11,291,40,25,0,1,1,1
88,0,0,0,1,11,225,28,24,0,1,2,0
89,1,0,0,0,11,155,34,25,0,2,0,1
90,0,0,0,1,11,225,28,24,0,1,2,0
91,0,0,1,0,11,179,40,22,1,2,0,1
92,1,0,0,0,11,225,28,24,0,1,2,0
93,0,0,0,1,11,260,36,23,0,4,0,1
94,0,0,0,1,11,248,47,32,0,2,1,0
95,0,0,0,1,11,225,28,24,0,1,2,0
96,1,0,0,0,11,289,33,30,0,2,1,1
97,0,0,0,1,11,291,40,25,0,1,1,0
98,0,0,0,1,12,248,47,32,0,2,1,0
99,0,0,1,0,12,118,37,28,0,0,0,1
100,0,0,0,1,12,118,50,31,0,1,0,0
101,0,0,0,1,12,235,37,29,1,1,1,1
102,0,0,0,1,12,225,28,24,0,1,2,0
103,0,0,0,1,12,260,36,23,0,4,0,1
104,0,0,1,0,12,118,37,28,0,0,0,1
105,0,0,0,1,12,361,28,27,0,1,4,1
106,0,0,0,1,12,225,28,24,0,1,2,0
107,0,0,0,1,12,260,36,23,0,4,0,0
108,0,0,0,1,12,225,28,24,0,1,2,0
109,0,0,0,1,12,361,28,27,0,1,4,1
110,0,0,0,1,12,118,37,28,0,0,0,0
111,0,0,1,0,12,246,41,23,0,0,0,1
112,0,0,0,1,12,225,28,24,0,1,2,0
113,0,0,0,1,1,225,28,24,0,1,2,0
114,0,0,1,0,1,118,37,28,0,0,0,0
115,0,0,0,1,1,118,37,28,0,0,0,0
116,0,0,1,0,1,155,34,25,0,2,0,1
117,0,0,0,1,1,225,28,24,0,1,2,0
118,0,0,0,1,1,184,27,21,0,0,0,0
119,0,0,0,1,1,225,28,24,0,1,2,0
120,0,0,0,1,1,225,28,24,0,1,2,0
121,0,0,0,1,1,118,37,28,0,0,0,0
122,0,0,0,1,1,225,28,24,0,1,2,0
123,0,0,0,1,1,118,37,28,0,0,0,0
124,0,0,0,1,1,118,37,28,0,0,0,0
125,0,0,0,1,1,118,37,28,0,0,0,0
126,0,0,0,1,1,118,37,28,0,0,0,0
127,0,0,0,1,1,118,37,28,0,0,0,0
128,0,0,0,1,1,118,37,28,0,0,0,0
129,0,0,1,0,1,179,30,19,1,0,0,1
130,0,0,1,0,1,289,33,30,0,2,1,1
131,0,0,0,1,1,118,37,28,0,0,0,0
132,0,0,0,1,1,184,27,21,0,0,0,0
133,0,0,0,1,1,118,37,28,0,0,0,0
134,0,0,0,1,1,118,37,28,0,0,0,0
135,0,0,0,1,1,225,28,24,0,1,2,0
136,0,0,0,1,1,289,33,30,0,2,1,0
137,0,0,0,1,2,184,27,21,0,0,0,0
138,1,0,0,0,2,246,41,23,0,0,0,1
139,1,0,0,0,2,179,38,31,0,0,0,1
140,0,0,0,1,2,155,34,25,0,2,0,0
141,0,0,0,1,2,189,33,25,0,2,2,1
142,0,0,0,1,2,260,36,23,0,4,0,0
143,0,0,0,1,2,289,33,30,0,2,1,1
144,1,0,0,0,2,388,50,24,0,0,0,1
145,1,0,0,0,2,388,50,24,0,0,0,1
146,0,0,0,1,2,225,28,24,0,1,2,0
147,0,0,0,1,2,225,28,24,0,1,2,0
148,0,0,0,1,2,179,30,19,1,0,0,0
149,0,0,0,1,2,184,27,21,0,0,0,1
150,0,0,0,1,2,225,28,24,0,1,2,0
151,0,0,1,0,2,330,28,25,1,0,0,1
152,0,0,0,1,2,330,28,25,1,0,0,0
153,0,0,0,1,2,225,28,24,0,1,2,0
154,0,0,1,0,2,189,33,25,0,2,2,1
155,0,0,0,1,3,291,32,23,0,0,0,0
156,0,0,1,0,3,260,36,23,0,4,0,1
157,0,0,1,0,3,157,29,22,0,0,0,0
158,0,1,0,0,3,179,40,22,1,2,0,1
159,0,0,0,1,3,291,40,25,0,1,1,1
160,1,0,0,0,3,260,36,23,0,4,0,1
161,1,0,0,0,3,179,30,19,1,0,0,1
162,1,0,0,0,3,248,47,32,0,2,1,0
163,1,0,0,0,3,260,36,23,0,4,0,1
164,1,0,0,0,3,179,40,22,1,2,0,1
165,1,0,0,0,3,155,34,25,0,2,0,1
166,0,0,0,1,3,260,36,23,0,4,0,1
167,1,0,0,0,3,155,34,25,0,2,0,1
168,1,0,0,0,3,289,33,30,0,2,1,1
169,1,0,0,0,3,179,40,22,1,2,0,1
170,0,0,0,1,3,260,36,23,0,4,0,1
171,0,0,0,1,3,225,28,24,0,1,2,0
172,1,0,0,0,3,279,39,24,0,2,0,1
173,1,0,0,0,3,179,38,31,0,0,0,1
174,0,0,0,1,3,225,28,24,0,1,2,0
175,1,0,0,0,3,225,28,24,0,1,2,1
176,1,0,0,0,3,179,30,19,1,0,0,0
177,1,0,0,0,3,225,28,24,0,1,2,1
178,1,0,0,0,3,225,28,24,0,1,2,1
179,1,0,0,0,3,179,38,31,0,0,0,0
180,1,0,0,0,3,279,39,24,0,2,0,1
181,0,0,0,1,3,225,28,24,0,1,2,0
182,1,0,0,0,3,248,47,32,0,2,1,0
183,0,0,0,1,3,225,28,24,0,1,2,0
184,0,0,0,1,4,291,40,25,0,1,1,0
185,0,0,0,1,4,225,28,24,0,1,2,0
186,0,0,0,1,4,155,34,25,0,2,0,0
187,1,0,0,0,4,246,41,23,0,0,0,1
188,0,0,0,1,4,155,34,25,0,2,0,0
189,0,0,0,1,4,225,28,24,0,1,2,0
190,0,0,0,1,4,260,36,23,0,4,0,1
191,1,0,0,0,4,179,38,31,0,0,0,1
192,0,0,0,1,4,118,50,31,0,1,0,0
193,0,0,0,1,4,291,40,25,0,1,1,0
194,1,0,0,0,4,246,41,23,0,0,0,1
195,0,0,0,1,4,291,40,25,0,1,1,0
196,0,0,0,1,4,248,47,32,0,2,1,1
197,0,0,1,0,4,260,36,23,0,4,0,1
198,0,0,1,0,4,289,33,30,0,2,1,1
199,1,0,0,0,4,155,34,25,0,2,0,1
200,0,0,1,0,4,378,36,21,0,2,4,1
201,1,0,0,0,4,289,33,30,0,2,1,1
202,1,0,0,0,4,235,37,29,1,1,1,0
203,0,0,0,0,4,235,48,33,0,1,5,0
204,1,0,0,0,5,289,33,30,0,2,1,1
205,0,0,0,1,5,155,34,25,0,2,0,0
206,0,0,0,1,5,155,34,25,0,2,0,0
207,0,0,1,0,5,179,38,31,0,0,0,1
208,0,0,1,0,5,225,28,24,0,1,2,1
209,1,0,0,0,5,184,27,21,0,0,0,1
210,0,0,0,1,5,155,34,25,0,2,0,0
211,1,0,0,0,5,179,38,31,0,0,0,0
212,1,0,0,0,5,289,33,30,0,2,1,1
213,0,0,0,0,5,279,39,24,0,2,0,0
214,0,0,0,0,5,330,28,25,1,0,0,0
215,0,0,0,0,5,378,36,21,0,2,4,0
216,0,0,0,0,5,388,50,24,0,0,0,0
217,1,0,0,0,5,179,38,31,0,0,0,0
218,1,0,0,0,5,118,50,31,0,1,0,1
219,0,0,0,1,5,361,28,27,0,1,4,1
220,0,0,1,0,6,246,41,23,0,0,0,1
221,0,0,0,1,6,361,28,27,0,1,4,1
222,1,0,0,0,6,246,41,23,0,0,0,1
223,0,0,0,1,6,291,40,25,0,1,1,1
224,1,0,0,0,6,246,41,23,0,0,0,1
225,1,0,0,0,6,179,38,31,0,0,0,1
226,0,0,0,1,6,155,34,25,0,2,0,1
227,1,0,0,0,6,246,41,23,0,0,0,1
228,1,0,0,0,6,118,50,31,0,1,0,1
229,1,0,0,0,6,235,37,29,1,1,1,1
230,0,0,0,1,6,118,50,31,0,1,0,0
231,1,0,0,0,6,118,50,31,0,1,0,1
232,0,0,0,1,6,378,36,21,0,2,4,1
233,1,0,0,0,6,179,38,31,0,0,0,0
234,0,0,0,1,6,289,49,36,0,0,2,0
235,0,0,0,1,6,225,28,24,0,1,2,0
236,0,0,1,0,7,155,34,25,0,2,0,1
237,1,0,0,0,7,118,50,31,0,1,0,1
238,1,0,0,0,7,118,37,28,0,0,0,1
239,0,0,0,1,7,118,37,28,0,0,0,1
240,0,0,0,1,7,330,28,25,1,0,0,1
241,0,0,1,0,7,179,30,19,1,0,0,1
242,0,0,0,1,7,155,34,25,0,2,0,0
243,1,0,0,0,7,330,28,25,1,0,0,1
244,1,0,0,0,7,330,28,25,1,0,0,1
245,0,0,0,1,7,157,29,22,0,0,0,0
246,0,0,0,1,7,361,28,27,0,1,4,1
247,0,0,0,1,7,289,33,30,0,2,1,1
248,0,0,0,1,7,179,38,31,0,0,0,1
249,0,0,1,0,7,289,33,30,0,2,1,1
250,0,0,1,0,7,289,33,30,0,2,1,1
251,0,0,0,0,7,260,36,23,0,4,0,0
252,0,0,1,0,8,289,33,30,0,2,1,1
253,0,0,1,0,8,157,29,22,0,0,0,0
254,0,0,0,1,8,289,33,30,0,2,1,0
255,0,0,1,0,8,228,58,22,0,2,1,1
256,1,0,0,0,8,300,43,25,0,2,1,0
257,1,0,0,0,8,300,43,25,0,2,1,0
258,0,0,0,1,8,260,36,23,0,4,0,1
259,0,0,0,1,8,289,33,30,0,2,1,1
260,0,0,0,1,8,248,47,32,0,2,1,0
261,1,0,0,0,8,268,33,25,1,0,0,1
262,0,0,0,1,8,179,30,19,1,0,0,0
263,1,0,0,0,8,118,50,31,0,1,0,0
264,0,0,0,1,8,248,47,32,0,2,1,0
265,0,0,0,1,8,235,37,29,1,1,1,0
266,0,0,0,1,8,118,50,31,0,1,0,0
267,0,0,1,0,8,235,37,29,1,1,1,1
268,1,0,0,0,8,361,28,27,0,1,4,1
269,1,0,0,0,8,184,27,21,0,0,0,1
270,1,0,0,0,9,179,38,31,0,0,0,1
271,0,0,0,1,9,179,38,31,0,0,0,0
272,0,0,1,0,9,289,33,30,0,2,1,1
273,0,0,0,0,9,235,43,38,0,1,0,0
274,1,0,0,0,9,246,41,23,0,0,0,1
275,0,0,0,1,9,291,40,25,0,1,1,0
276,0,0,0,0,9,231,39,35,0,2,2,0
277,0,0,0,0,9,291,32,23,0,0,0,0
278,1,0,0,0,9,179,38,31,0,0,0,1
279,1,0,0,0,9,246,41,23,0,0,0,1
280,0,0,0,1,9,179,38,31,0,0,0,0
281,0,0,0,1,9,291,40,25,0,1,1,1
282,0,0,0,1,9,260,36,23,0,4,0,1
283,0,0,0,1,9,235,43,38,0,1,0,1
284,0,0,0,1,9,118,50,31,0,1,0,0
285,0,0,0,0,9,235,43,38,0,1,0,0
286,0,0,0,1,9,291,40,25,0,1,1,0
287,1,0,0,0,9,291,40,25,0,1,1,1
288,1,0,0,0,9,179,38,31,0,0,0,1
289,0,0,0,1,10,289,33,30,0,2,1,1
290,0,0,0,1,10,235,37,29,1,1,1,1
291,0,0,0,1,10,289,33,30,0,2,1,1
292,0,0,0,1,10,289,33,30,0,2,1,1
293,0,0,0,0,10,118,50,31,0,1,0,0
294,0,0,0,0,10,248,47,32,0,2,1,0
295,1,0,0,0,10,179,30,19,1,0,0,1
296,1,0,0,0,10,118,37,28,0,0,0,0
297,0,0,0,1,10,369,31,25,0,3,0,1
298,0,0,0,1,10,179,38,31,0,0,0,0
299,1,0,0,0,10,179,30,19,1,0,0,1
300,0,0,0,0,10,235,43,38,0,1,0,0
301,0,0,1,0,10,289,33,30,0,2,1,1
302,0,0,0,1,10,260,36,23,0,4,0,0
303,0,0,0,0,10,235,43,38,0,1,0,0
304,0,0,0,1,10,235,43,38,0,1,0,0
305,0,0,0,1,10,235,43,38,0,1,0,0
306,0,0,0,1,10,118,50,31,0,1,0,0
307,0,0,0,1,10,291,40,25,0,1,1,1
308,0,0,0,1,10,179,30,19,1,0,0,1
309,0,0,0,1,10,118,50,31,0,1,0,0
310,1,0,0,0,10,361,28,27,0,1,4,1
311,0,0,0,0,10,260,36,23,0,4,0,0
312,0,0,0,0,10,291,40,25,0,1,1,0
313,0,0,0,0,10,157,29,22,0,0,0,0
314,1,0,0,0,10,179,30,19,1,0,0,1
315,1,0,0,0,10,179,30,19,1,0,0,1
316,0,0,0,1,10,118,50,31,0,1,0,0
317,1,0,0,0,11,118,37,28,0,0,0,1
318,0,0,0,1,11,248,47,32,0,2,1,0
319,1,0,0,0,11,179,38,31,0,0,0,1
320,0,0,0,1,11,260,36,23,0,4,0,0
321,0,0,0,1,11,291,40,25,0,1,1,0
322,1,0,0,0,11,378,36,21,0,2,4,1
323,1,0,0,0,11,155,34,25,0,2,0,1
324,0,0,0,1,11,235,43,38,0,1,0,1
325,0,0,0,0,11,330,28,25,1,0,0,0
326,0,0,1,0,11,235,37,29,1,1,1,0
327,1,0,0,0,11,118,37,28,0,0,0,0
328,0,0,0,1,11,235,37,29,1,1,1,0
329,0,0,0,1,11,179,38,31,0,0,0,0
330,1,0,0,0,11,246,41,23,0,0,0,1
331,1,0,0,0,11,291,40,25,0,1,1,1
332,1,0,0,0,11,246,41,23,0,0,0,1
333,0,0,0,1,11,179,38,31,0,0,0,0
334,1,0,0,0,11,260,36,23,0,4,0,1
335,0,1,0,0,11,260,36,23,0,4,0,1
336,0,0,0,0,11,378,36,21,0,2,4,0
337,0,0,0,0,11,279,39,24,0,2,0,0
338,0,0,0,1,11,179,38,31,0,0,0,0
339,1,0,0,0,12,225,28,24,0,1,2,0
340,0,0,0,1,12,179,38,31,0,0,0,0
341,0,0,0,1,12,179,38,31,0,0,0,0
342,0,0,0,1,12,235,37,29,1,1,1,0
343,0,0,0,1,12,118,50,31,0,1,0,0
344,0,0,0,1,12,260,36,23,0,4,0,1
345,1,0,0,0,12,246,41,23,0,0,0,1
346,0,0,0,1,12,179,38,31,0,0,0,0
347,0,0,0,1,12,179,38,31,0,0,0,0
348,0,0,0,1,12,179,30,19,1,0,0,0
349,0,0,0,1,12,118,37,28,0,0,0,1
350,0,0,0,1,12,235,37,29,1,1,1,0
351,0,0,0,1,12,179,38,31,0,0,0,0
352,1,0,0,0,12,235,43,38,0,1,0,1
353,1,0,0,0,12,235,37,29,1,1,1,1
354,0,0,0,1,12,260,36,23,0,4,0,1
355,0,0,0,1,12,157,29,22,0,0,0,0
356,0,0,0,1,12,179,38,31,0,0,0,0
357,0,0,1,0,12,289,33,30,0,2,1,1
358,0,0,0,1,1,225,28,24,0,1,2,1
359,0,0,1,0,1,118,37,28,0,0,0,1
360,0,0,0,1,1,155,34,25,0,2,0,0
361,1,0,0,0,1,235,37,29,1,1,1,0
362,0,0,0,1,1,155,34,25,0,2,0,1
363,0,0,0,1,1,289,33,30,0,2,1,1
364,1,0,0,0,1,291,40,25,0,1,1,1
365,0,0,0,1,1,235,43,38,0,1,0,1
366,0,0,0,1,1,118,50,31,0,1,0,1
367,0,0,0,1,1,179,38,31,0,0,0,0
368,0,0,0,1,1,179,38,31,0,0,0,0
369,0,0,0,1,2,118,37,28,0,0,0,0
370,0,0,0,1,2,179,38,31,0,0,0,0
371,1,0,0,0,2,225,28,24,0,1,2,0
372,0,0,0,1,2,289,33,30,0,2,1,0
373,0,0,0,1,2,260,36,23,0,4,0,0
374,0,0,0,1,2,179,38,31,0,0,0,0
375,0,0,0,1,2,179,38,31,0,0,0,0
376,0,0,0,1,2,179,38,31,0,0,0,0
377,1,0,0,0,2,179,38,31,0,0,0,1
378,0,0,0,1,2,246,41,23,0,0,0,1
379,0,0,0,1,2,179,38,31,0,0,0,0
380,0,0,0,1,2,189,33,25,0,2,2,1
381,0,0,0,1,2,179,38,31,0,0,0,0
382,0,0,0,1,2,246,41,23,0,0,0,0
383,0,0,0,1,2,291,40,25,0,1,1,0
384,1,0,0,0,2,157,29,22,0,0,0,1
385,0,0,0,1,2,179,38,31,0,0,0,0
386,0,0,0,1,2,179,38,31,0,0,0,0
387,1,0,0,0,2,246,41,23,0,0,0,1
388,0,0,0,1,2,179,38,31,0,0,0,0
389,0,0,0,1,2,179,38,31,0,0,0,0
390,0,0,1,0,3,118,37,28,0,0,0,1
391,0,0,1,0,3,246,41,23,0,0,0,1
392,0,0,0,1,3,246,41,23,0,0,0,0
393,0,0,0,1,3,260,36,23,0,4,0,1
394,0,0,0,1,3,179,38,31,0,0,0,0
395,0,0,0,1,3,235,37,29,1,1,1,1
396,0,0,0,1,3,179,40,22,1,2,0,1
397,0,0,0,1,3,378,36,21,0,2,4,1
398,0,0,0,1,3,179,38,31,0,0,0,1
399,0,0,0,1,3,361,28,27,0,1,4,1
400,0,0,0,0,3,369,31,25,0,3,0,0
401,0,0,1,0,3,235,37,29,1,1,1,1
402,0,0,0,1,3,118,50,31,0,1,0,0
403,1,0,0,0,3,118,50,31,0,1,0,0
404,1,0,0,0,3,118,50,31,0,1,0,1
405,0,0,0,0,3,235,37,29,1,1,1,0
406,0,0,0,0,3,246,41,23,0,0,0,0
407,0,0,0,0,3,118,50,31,0,1,0,0
408,0,0,0,1,3,179,38,31,0,0,0,1
409,0,0,0,1,3,289,33,30,0,2,1,1
410,0,0,1,0,3,260,36,23,0,4,0,1
411,0,0,0,1,3,246,41,23,0,0,0,0
412,0,0,0,1,4,179,38,31,0,0,0,1
413,0,0,0,1,4,260,36,23,0,4,0,0
414,0,0,0,1,4,330,28,25,1,0,0,1
415,0,0,0,1,4,369,31,25,0,3,0,1
416,0,0,0,1,4,248,47,32,0,2,1,1
417,0,0,0,1,4,330,28,25,1,0,0,1
418,0,0,0,1,4,179,38,31,0,0,0,1
419,0,0,0,1,4,118,50,31,0,1,0,0
420,1,0,0,0,4,118,50,31,0,1,0,1
421,0,0,0,1,4,300,43,25,0,2,1,1
422,0,0,0,1,4,260,36,23,0,4,0,1
423,0,0,0,1,4,179,38,31,0,0,0,1
424,1,0,0,0,4,118,37,28,0,0,0,0
425,1,0,0,0,5,235,43,38,0,1,0,1
426,0,0,0,1,5,248,47,32,0,2,1,0
427,1,0,0,0,5,369,31,25,0,3,0,1
428,0,0,0,1,5,179,30,19,1,0,0,0
429,0,0,0,1,5,179,38,31,0,0,0,1
430,0,0,0,1,5,361,28,27,0,1,4,0
431,0,0,0,1,5,260,36,23,0,4,0,0
432,1,0,0,0,5,179,40,22,1,2,0,0
433,1,0,0,0,5,179,40,22,1,2,0,0
434,0,0,1,0,5,228,58,22,0,2,1,1
435,0,0,0,1,5,225,28,24,0,1,2,0
436,1,0,0,0,5,330,28,25,1,0,0,1
437,0,0,0,1,5,179,30,19,1,0,0,0
438,0,0,0,1,5,118,37,28,0,0,0,0
439,1,0,0,0,5,235,37,29,1,1,1,1
440,0,0,0,1,5,179,30,19,1,0,0,0
441,0,0,0,1,6,118,37,28,0,0,0,0
442,0,0,0,1,6,179,38,31,0,0,0,0
443,0,0,0,1,6,118,37,28,0,0,0,0
444,0,0,0,1,6,225,28,24,0,1,2,1
445,0,0,0,1,6,260,36,23,0,4,0,1
446,0,0,0,0,6,179,38,31,0,0,0,0
447,1,0,0,0,6,291,40,25,0,1,1,1
448,0,0,0,1,6,179,38,31,0,0,0,1
449,0,0,0,1,6,246,41,23,0,0,0,0
450,0,0,0,1,6,179,38,31,0,0,0,1
451,0,0,0,1,6,235,43,38,0,1,0,1
452,0,0,0,1,6,179,38,31,0,0,0,0
453,0,0,0,1,6,225,28,24,0,1,2,0
454,0,0,0,1,6,118,50,31,0,1,0,0
455,1,0,0,0,6,179,38,31,0,0,0,1
456,0,0,1,0,6,179,30,19,1,0,0,0
457,0,0,0,1,6,246,41,23,0,0,0,0
458,1,0,0,0,6,330,28,25,1,0,0,0
459,1,0,0,0,6,235,37,29,1,1,1,1
460,0,0,0,1,7,179,30,19,1,0,0,0
461,0,0,0,1,7,225,28,24,0,1,2,1
462,1,0,0,0,7,260,36,23,0,4,0,1
463,1,0,0,0,7,268,33,25,1,0,0,1
464,0,0,0,1,7,330,28,25,1,0,0,1
465,0,0,0,1,7,118,37,28,0,0,0,1
466,0,0,0,1,7,260,36,23,0,4,0,1
467,0,0,0,1,7,118,37,28,0,0,0,1
468,0,1,0,0,7,300,43,25,0,2,1,1
469,0,0,0,1,7,235,48,33,0,1,5,0
470,0,0,0,1,7,246,41,23,0,0,0,0
471,1,0,0,0,7,225,28,24,0,1,2,1
472,0,0,0,1,7,179,38,31,0,0,0,0
473,0,0,0,1,7,118,50,31,0,1,0,0
474,0,0,0,1,7,361,28,27,0,1,4,1
475,0,0,0,1,7,289,33,30,0,2,1,1
476,0,0,0,1,7,235,43,38,0,1,0,1
477,0,0,0,1,7,246,41,23,0,0,0,0
478,0,0,0,1,7,291,40,25,0,1,1,0
479,0,0,0,1,7,279,39,24,0,2,0,0
480,0,0,0,1,8,179,38,31,0,0,0,1
481,0,0,0,1,8,179,40,22,1,2,0,0
482,0,0,0,1,8,246,41,23,0,0,0,1
483,0,0,0,1,8,118,37,28,0,0,0,1
484,0,0,0,1,8,289,33,30,0,2,1,1
485,0,0,0,1,8,235,43,38,0,1,0,1
486,0,0,0,1,8,291,40,25,0,1,1,1
487,0,0,0,1,8,179,38,31,0,0,0,1
488,0,0,0,1,8,179,40,22,1,2,0,1
489,0,0,0,1,8,330,28,25,1,0,0,1
490,0,0,0,1,8,235,37,29,1,1,1,1
491,0,0,0,1,8,246,41,23,0,0,0,0
492,0,0,0,1,8,118,37,28,0,0,0,1
493,0,0,0,1,8,291,40,25,0,1,1,0
494,0,0,0,1,8,260,36,23,0,4,0,0
495,0,0,0,1,9,246,41,23,0,0,0,0
496,0,0,0,1,9,246,41,23,0,0,0,0
497,0,0,0,1,9,118,37,28,0,0,0,0
498,0,0,0,1,9,155,34,25,0,2,0,0
499,0,0,0,1,9,291,40,25,0,1,1,0
500,0,0,0,1,9,179,30,19,1,0,0,1
501,0,0,0,1,9,248,47,32,0,2,1,0
502,0,0,0,1,9,179,38,31,0,0,0,1
503,0,0,0,1,9,225,28,24,0,1,2,0
504,0,0,0,1,9,179,30,19,1,0,0,0
505,0,0,0,1,9,369,31,25,0,3,0,1
506,0,0,0,1,9,361,28,27,0,1,4,1
507,1,0,0,0,10,289,49,36,0,0,2,0
508,1,0,0,0,10,235,32,25,1,0,0,0
509,0,0,0,1,10,246,41,23,0,0,0,1
510,1,0,0,0,10,289,49,36,0,0,2,0
511,0,0,0,1,10,291,40,25,0,1,1,0
512,0,0,0,1,10,118,37,28,0,0,0,0
513,0,0,0,1,10,289,49,36,0,0,2,0
514,0,0,0,1,10,291,40,25,0,1,1,0
515,0,0,0,1,10,225,28,24,0,1,2,0
516,0,0,0,1,10,369,31,25,0,3,0,1
517,0,0,0,1,10,369,31,25,0,3,0,0
518,0,0,0,1,10,225,28,24,0,1,2,1
519,0,0,0,1,10,369,31,25,0,3,0,1
520,0,0,0,1,10,179,38,31,0,0,0,0
521,1,0,0,0,10,228,58,22,0,2,1,0
522,0,0,0,1,10,291,40,25,0,1,1,0
523,1,0,0,0,10,369,31,25,0,3,0,1
524,1,0,0,0,10,225,28,24,0,1,2,0
525,1,0,0,0,10,369,31,25,0,3,0,1
526,1,0,0,0,10,225,28,24,0,1,2,0
527,0,0,0,1,10,189,33,25,0,2,2,1
528,1,0,0,0,10,235,32,25,1,0,0,1
529,1,0,0,0,10,248,47,32,0,2,1,1
530,0,0,0,0,10,225,28,24,0,1,2,0
531,1,0,0,0,10,225,28,24,0,1,2,0
532,0,0,1,0,11,179,38,31,0,0,0,0
533,0,0,0,1,11,118,37,28,0,0,0,0
534,1,0,0,0,11,330,28,25,1,0,0,1
535,0,0,0,1,11,179,38,31,0,0,0,0
536,1,0,0,0,11,118,37,28,0,0,0,1
537,0,0,0,1,11,289,33,30,0,2,1,1
538,1,0,0,0,11,235,32,25,1,0,0,1
539,0,0,0,1,11,225,28,24,0,1,2,1
540,0,0,0,1,11,361,28,27,0,1,4,1
541,0,0,0,1,11,291,40,25,0,1,1,0
542,1,0,0,0,11,118,37,28,0,0,0,0
543,1,0,0,0,11,225,28,24,0,1,2,0
544,0,0,0,1,11,179,38,31,0,0,0,0
545,0,0,0,1,11,118,37,28,0,0,0,1
546,1,0,0,0,11,118,37,28,0,0,0,1
547,0,0,0,1,11,225,28,24,0,1,2,0
548,0,0,0,0,11,291,40,25,0,1,1,0
549,0,0,0,0,11,289,33,30,0,2,1,0
550,1,0,0,0,11,248,47,32,0,2,1,1
551,0,0,0,0,11,235,43,38,0,1,0,0
552,0,0,0,1,11,225,28,24,0,1,2,0
553,0,0,0,1,11,369,31,25,0,3,0,1
554,0,0,0,1,11,361,28,27,0,1,4,0
555,1,0,0,0,12,179,38,31,0,0,0,1
556,0,0,0,1,12,291,40,25,0,1,1,0
557,0,0,0,1,12,225,28,24,0,1,2,0
558,1,0,0,0,12,179,30,19,1,0,0,0
559,0,0,0,1,12,225,28,24,0,1,2,0
560,0,0,0,1,12,225,28,24,0,1,2,0
561,1,0,0,0,12,361,28,27,0,1,4,1
562,0,0,1,0,12,179,40,22,1,2,0,0
563,0,0,0,1,12,235,43,38,0,1,0,1
564,0,0,1,0,12,233,31,21,1,1,8,1
565,1,0,0,0,12,179,30,19,1,0,0,1
566,0,0,0,1,12,225,28,24,0,1,2,0
567,0,0,0,1,12,225,28,24,0,1,2,0
568,0,0,0,1,12,225,28,24,0,1,2,0
569,0,0,1,0,12,155,34,25,0,2,0,1
570,1,0,0,0,1,179,30,19,1,0,0,1
571,1,0,0,0,1,179,30,19,1,0,0,1
572,0,0,0,1,1,179,40,22,1,2,0,0
573,0,0,0,1,1,179,40,22,1,2,0,0
574,1,0,0,0,1,179,30,19,1,0,0,0
575,0,0,0,1,1,179,40,22,1,2,0,0
576,1,0,0,0,1,289,49,36,0,0,2,1
577,0,0,1,0,1,179,40,22,1,2,0,0
578,0,0,0,1,1,179,30,19,1,0,0,0
579,0,0,1,0,1,155,34,25,0,2,0,1
580,0,0,0,1,1,179,30,19,1,0,0,0
581,0,0,0,1,1,179,38,31,0,0,0,0
582,1,0,0,0,1,289,33,30,0,2,1,1
583,0,0,0,1,1,179,38,31,0,0,0,0
584,0,0,0,1,1,179,38,31,0,0,0,0
585,1,0,0,0,2,179,38,31,0,0,0,1
586,0,0,0,1,2,225,28,24,0,1,2,0
587,1,0,0,0,2,248,47,32,0,2,1,1
588,0,0,0,1,2,179,38,31,0,0,0,0
589,0,0,0,1,2,225,28,24,0,1,2,0
590,0,0,0,1,2,179,38,31,0,0,0,0
591,0,0,0,1,2,179,30,19,1,0,0,0
592,0,0,0,1,2,225,41,28,1,2,2,0
593,0,0,0,1,2,179,38,31,0,0,0,0
594,0,0,1,0,2,233,31,21,1,1,8,0
595,0,0,0,1,2,179,38,31,0,0,0,0
596,1,0,0,0,2,225,28,24,0,1,2,1
597,0,0,0,1,2,179,38,31,0,0,0,0
598,0,0,0,1,2,179,38,31,0,0,0,0
599,0,0,0,1,2,225,28,24,0,1,2,0
600,1,0,0,0,2,179,30,19,1,0,0,0
601,0,0,0,1,2,179,40,22,1,2,0,0
602,0,0,0,1,2,179,38,31,0,0,0,0
603,1,0,0,0,2,233,31,21,1,1,8,0
604,0,0,0,1,2,179,30,19,1,0,0,0
605,0,0,0,1,2,179,38,31,0,0,0,0
606,1,0,0,0,2,179,38,31,0,0,0,1
607,0,0,0,1,2,179,38,31,0,0,0,0
608,0,0,0,1,2,155,34,25,0,2,0,1
609,0,0,0,1,2,235,32,25,1,0,0,0
610,0,0,0,1,2,179,38,31,0,0,0,0
611,1,0,0,0,2,225,28,24,0,1,2,0
612,0,0,0,1,2,179,38,31,0,0,0,0
613,0,0,0,1,2,248,47,32,0,2,1,0
614,0,0,0,1,2,225,28,24,0,1,2,0
615,0,0,0,1,2,179,38,31,0,0,0,0
616,0,0,0,1,2,179,38,31,0,0,0,0
617,0,0,0,1,2,235,32,25,1,0,0,0

In [300]:
data_with_targets.iloc[:,:-1]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,7,289,33,30,0,2,1
1,0,0,0,0,7,118,50,31,0,1,0
2,0,0,0,1,7,179,38,31,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0
4,0,0,0,1,7,289,33,30,0,2,1
5,0,0,0,1,7,179,38,31,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4
7,0,0,0,1,7,260,36,23,0,4,0
8,0,0,1,0,7,155,34,25,0,2,0
9,0,0,0,1,7,235,37,29,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0
11,1,0,0,0,7,260,36,23,0,4,0
12,1,0,0,0,7,260,36,23,0,4,0
13,1,0,0,0,7,179,38,31,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0
15,1,0,0,0,7,246,41,23,0,0,0
16,0,0,0,1,7,179,38,31,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0
18,1,0,0,0,7,189,33,25,0,2,2
19,0,0,0,1,8,248,47,32,0,2,1
20,1,0,0,0,8,330,28,25,1,0,0
21,1,0,0,0,8,179,38,31,0,0,0
22,1,0,0,0,8,361,28,27,0,1,4
23,0,0,0,1,8,260,36,23,0,4,0
24,0,0,1,0,8,289,33,30,0,2,1
25,0,0,0,1,8,361,28,27,0,1,4
26,0,0,0,1,8,289,33,30,0,2,1
27,0,0,0,1,8,157,29,22,0,0,0
28,0,0,1,0,8,289,33,30,0,2,1
29,0,0,0,1,8,179,38,31,0,0,0
30,0,0,1,0,8,179,38,31,0,0,0
31,0,0,1,0,8,235,48,33,0,1,5
32,0,0,0,1,8,235,37,29,1,1,1
33,0,0,1,0,8,235,48,33,0,1,5
34,0,0,0,1,8,179,38,31,0,0,0
35,0,0,0,1,8,361,28,27,0,1,4
36,0,0,0,1,8,289,33,30,0,2,1
37,1,0,0,0,8,291,32,23,0,0,0
38,0,0,0,1,8,235,48,33,0,1,5
39,0,0,0,1,8,260,36,23,0,4,0
40,0,0,0,1,9,184,27,21,0,0,0
41,0,0,0,1,9,118,37,28,0,0,0
42,0,0,0,1,9,179,38,31,0,0,0
43,0,0,1,0,9,235,43,38,0,1,0
44,0,0,0,1,9,155,34,25,0,2,0
45,0,0,0,1,9,118,37,28,0,0,0
46,0,0,0,1,9,179,38,31,0,0,0
47,0,0,0,1,9,291,40,25,0,1,1
48,0,0,0,1,9,260,36,23,0,4,0
49,1,0,0,0,9,291,40,25,0,1,1
50,0,0,0,0,9,260,36,23,0,4,0
51,0,0,0,0,9,225,28,24,0,1,2
52,0,0,0,1,9,225,28,24,0,1,2
53,0,0,0,1,9,118,37,28,0,0,0
54,0,0,0,0,9,289,33,30,0,2,1
55,0,0,0,0,9,118,50,31,0,1,0
56,0,0,1,0,9,225,28,24,0,1,2
57,0,0,0,1,9,179,38,31,0,0,0
58,0,0,0,0,9,369,31,25,0,3,0
59,0,0,0,1,9,248,47,32,0,2,1
60,0,0,0,1,9,179,38,31,0,0,0
61,0,0,0,1,9,260,36,23,0,4,0
62,0,0,0,1,10,179,38,31,0,0,0
63,0,0,0,1,10,118,37,28,0,0,0
64,0,0,0,0,10,118,50,31,0,1,0
65,0,0,0,1,10,179,30,19,1,0,0
66,0,0,0,1,10,179,38,31,0,0,0
67,0,0,0,1,10,225,28,24,0,1,2
68,0,0,0,1,10,118,37,28,0,0,0
69,0,0,0,1,10,225,28,24,0,1,2
70,0,0,0,1,10,248,47,32,0,2,1
71,0,0,0,1,10,291,40,25,0,1,1
72,0,0,0,1,10,179,38,31,0,0,0
73,0,0,0,1,10,225,28,24,0,1,2
74,0,0,1,0,10,260,36,23,0,4,0
75,1,0,0,0,10,291,40,25,0,1,1
76,0,0,0,1,10,225,28,24,0,1,2
77,0,0,0,1,10,289,33,30,0,2,1
78,0,0,0,1,10,361,28,27,0,1,4
79,0,0,0,1,10,260,36,23,0,4,0
80,0,0,0,1,11,179,38,31,0,0,0
81,0,0,0,1,11,225,28,24,0,1,2
82,1,0,0,0,11,179,38,31,0,0,0
83,0,0,1,0,11,179,40,22,1,2,0
84,0,0,0,1,11,291,40,25,0,1,1
85,1,0,0,0,11,155,34,25,0,2,0
86,0,0,0,1,11,189,33,25,0,2,2
87,1,0,0,0,11,291,40,25,0,1,1
88,0,0,0,1,11,225,28,24,0,1,2
89,1,0,0,0,11,155,34,25,0,2,0
90,0,0,0,1,11,225,28,24,0,1,2
91,0,0,1,0,11,179,40,22,1,2,0
92,1,0,0,0,11,225,28,24,0,1,2
93,0,0,0,1,11,260,36,23,0,4,0
94,0,0,0,1,11,248,47,32,0,2,1
95,0,0,0,1,11,225,28,24,0,1,2
96,1,0,0,0,11,289,33,30,0,2,1
97,0,0,0,1,11,291,40,25,0,1,1
98,0,0,0,1,12,248,47,32,0,2,1
99,0,0,1,0,12,118,37,28,0,0,0
100,0,0,0,1,12,118,50,31,0,1,0
101,0,0,0,1,12,235,37,29,1,1,1
102,0,0,0,1,12,225,28,24,0,1,2
103,0,0,0,1,12,260,36,23,0,4,0
104,0,0,1,0,12,118,37,28,0,0,0
105,0,0,0,1,12,361,28,27,0,1,4
106,0,0,0,1,12,225,28,24,0,1,2
107,0,0,0,1,12,260,36,23,0,4,0
108,0,0,0,1,12,225,28,24,0,1,2
109,0,0,0,1,12,361,28,27,0,1,4
110,0,0,0,1,12,118,37,28,0,0,0
111,0,0,1,0,12,246,41,23,0,0,0
112,0,0,0,1,12,225,28,24,0,1,2
113,0,0,0,1,1,225,28,24,0,1,2
114,0,0,1,0,1,118,37,28,0,0,0
115,0,0,0,1,1,118,37,28,0,0,0
116,0,0,1,0,1,155,34,25,0,2,0
117,0,0,0,1,1,225,28,24,0,1,2
118,0,0,0,1,1,184,27,21,0,0,0
119,0,0,0,1,1,225,28,24,0,1,2
120,0,0,0,1,1,225,28,24,0,1,2
121,0,0,0,1,1,118,37,28,0,0,0
122,0,0,0,1,1,225,28,24,0,1,2
123,0,0,0,1,1,118,37,28,0,0,0
124,0,0,0,1,1,118,37,28,0,0,0
125,0,0,0,1,1,118,37,28,0,0,0
126,0,0,0,1,1,118,37,28,0,0,0
127,0,0,0,1,1,118,37,28,0,0,0
128,0,0,0,1,1,118,37,28,0,0,0
129,0,0,1,0,1,179,30,19,1,0,0
130,0,0,1,0,1,289,33,30,0,2,1
131,0,0,0,1,1,118,37,28,0,0,0
132,0,0,0,1,1,184,27,21,0,0,0
133,0,0,0,1,1,118,37,28,0,0,0
134,0,0,0,1,1,118,37,28,0,0,0
135,0,0,0,1,1,225,28,24,0,1,2
136,0,0,0,1,1,289,33,30,0,2,1
137,0,0,0,1,2,184,27,21,0,0,0
138,1,0,0,0,2,246,41,23,0,0,0
139,1,0,0,0,2,179,38,31,0,0,0
140,0,0,0,1,2,155,34,25,0,2,0
141,0,0,0,1,2,189,33,25,0,2,2
142,0,0,0,1,2,260,36,23,0,4,0
143,0,0,0,1,2,289,33,30,0,2,1
144,1,0,0,0,2,388,50,24,0,0,0
145,1,0,0,0,2,388,50,24,0,0,0
146,0,0,0,1,2,225,28,24,0,1,2
147,0,0,0,1,2,225,28,24,0,1,2
148,0,0,0,1,2,179,30,19,1,0,0
149,0,0,0,1,2,184,27,21,0,0,0
150,0,0,0,1,2,225,28,24,0,1,2
151,0,0,1,0,2,330,28,25,1,0,0
152,0,0,0,1,2,330,28,25,1,0,0
153,0,0,0,1,2,225,28,24,0,1,2
154,0,0,1,0,2,189,33,25,0,2,2
155,0,0,0,1,3,291,32,23,0,0,0
156,0,0,1,0,3,260,36,23,0,4,0
157,0,0,1,0,3,157,29,22,0,0,0
158,0,1,0,0,3,179,40,22,1,2,0
159,0,0,0,1,3,291,40,25,0,1,1
160,1,0,0,0,3,260,36,23,0,4,0
161,1,0,0,0,3,179,30,19,1,0,0
162,1,0,0,0,3,248,47,32,0,2,1
163,1,0,0,0,3,260,36,23,0,4,0
164,1,0,0,0,3,179,40,22,1,2,0
165,1,0,0,0,3,155,34,25,0,2,0
166,0,0,0,1,3,260,36,23,0,4,0
167,1,0,0,0,3,155,34,25,0,2,0
168,1,0,0,0,3,289,33,30,0,2,1
169,1,0,0,0,3,179,40,22,1,2,0
170,0,0,0,1,3,260,36,23,0,4,0
171,0,0,0,1,3,225,28,24,0,1,2
172,1,0,0,0,3,279,39,24,0,2,0
173,1,0,0,0,3,179,38,31,0,0,0
174,0,0,0,1,3,225,28,24,0,1,2
175,1,0,0,0,3,225,28,24,0,1,2
176,1,0,0,0,3,179,30,19,1,0,0
177,1,0,0,0,3,225,28,24,0,1,2
178,1,0,0,0,3,225,28,24,0,1,2
179,1,0,0,0,3,179,38,31,0,0,0
180,1,0,0,0,3,279,39,24,0,2,0
181,0,0,0,1,3,225,28,24,0,1,2
182,1,0,0,0,3,248,47,32,0,2,1
183,0,0,0,1,3,225,28,24,0,1,2
184,0,0,0,1,4,291,40,25,0,1,1
185,0,0,0,1,4,225,28,24,0,1,2
186,0,0,0,1,4,155,34,25,0,2,0
187,1,0,0,0,4,246,41,23,0,0,0
188,0,0,0,1,4,155,34,25,0,2,0
189,0,0,0,1,4,225,28,24,0,1,2
190,0,0,0,1,4,260,36,23,0,4,0
191,1,0,0,0,4,179,38,31,0,0,0
192,0,0,0,1,4,118,50,31,0,1,0
193,0,0,0,1,4,291,40,25,0,1,1
194,1,0,0,0,4,246,41,23,0,0,0
195,0,0,0,1,4,291,40,25,0,1,1
196,0,0,0,1,4,248,47,32,0,2,1
197,0,0,1,0,4,260,36,23,0,4,0
198,0,0,1,0,4,289,33,30,0,2,1
199,1,0,0,0,4,155,34,25,0,2,0
200,0,0,1,0,4,378,36,21,0,2,4
201,1,0,0,0,4,289,33,30,0,2,1
202,1,0,0,0,4,235,37,29,1,1,1
203,0,0,0,0,4,235,48,33,0,1,5
204,1,0,0,0,5,289,33,30,0,2,1
205,0,0,0,1,5,155,34,25,0,2,0
206,0,0,0,1,5,155,34,25,0,2,0
207,0,0,1,0,5,179,38,31,0,0,0
208,0,0,1,0,5,225,28,24,0,1,2
209,1,0,0,0,5,184,27,21,0,0,0
210,0,0,0,1,5,155,34,25,0,2,0
211,1,0,0,0,5,179,38,31,0,0,0
212,1,0,0,0,5,289,33,30,0,2,1
213,0,0,0,0,5,279,39,24,0,2,0
214,0,0,0,0,5,330,28,25,1,0,0
215,0,0,0,0,5,378,36,21,0,2,4
216,0,0,0,0,5,388,50,24,0,0,0
217,1,0,0,0,5,179,38,31,0,0,0
218,1,0,0,0,5,118,50,31,0,1,0
219,0,0,0,1,5,361,28,27,0,1,4
220,0,0,1,0,6,246,41,23,0,0,0
221,0,0,0,1,6,361,28,27,0,1,4
222,1,0,0,0,6,246,41,23,0,0,0
223,0,0,0,1,6,291,40,25,0,1,1
224,1,0,0,0,6,246,41,23,0,0,0
225,1,0,0,0,6,179,38,31,0,0,0
226,0,0,0,1,6,155,34,25,0,2,0
227,1,0,0,0,6,246,41,23,0,0,0
228,1,0,0,0,6,118,50,31,0,1,0
229,1,0,0,0,6,235,37,29,1,1,1
230,0,0,0,1,6,118,50,31,0,1,0
231,1,0,0,0,6,118,50,31,0,1,0
232,0,0,0,1,6,378,36,21,0,2,4
233,1,0,0,0,6,179,38,31,0,0,0
234,0,0,0,1,6,289,49,36,0,0,2
235,0,0,0,1,6,225,28,24,0,1,2
236,0,0,1,0,7,155,34,25,0,2,0
237,1,0,0,0,7,118,50,31,0,1,0
238,1,0,0,0,7,118,37,28,0,0,0
239,0,0,0,1,7,118,37,28,0,0,0
240,0,0,0,1,7,330,28,25,1,0,0
241,0,0,1,0,7,179,30,19,1,0,0
242,0,0,0,1,7,155,34,25,0,2,0
243,1,0,0,0,7,330,28,25,1,0,0
244,1,0,0,0,7,330,28,25,1,0,0
245,0,0,0,1,7,157,29,22,0,0,0
246,0,0,0,1,7,361,28,27,0,1,4
247,0,0,0,1,7,289,33,30,0,2,1
248,0,0,0,1,7,179,38,31,0,0,0
249,0,0,1,0,7,289,33,30,0,2,1
250,0,0,1,0,7,289,33,30,0,2,1
251,0,0,0,0,7,260,36,23,0,4,0
252,0,0,1,0,8,289,33,30,0,2,1
253,0,0,1,0,8,157,29,22,0,0,0
254,0,0,0,1,8,289,33,30,0,2,1
255,0,0,1,0,8,228,58,22,0,2,1
256,1,0,0,0,8,300,43,25,0,2,1
257,1,0,0,0,8,300,43,25,0,2,1
258,0,0,0,1,8,260,36,23,0,4,0
259,0,0,0,1,8,289,33,30,0,2,1
260,0,0,0,1,8,248,47,32,0,2,1
261,1,0,0,0,8,268,33,25,1,0,0
262,0,0,0,1,8,179,30,19,1,0,0
263,1,0,0,0,8,118,50,31,0,1,0
264,0,0,0,1,8,248,47,32,0,2,1
265,0,0,0,1,8,235,37,29,1,1,1
266,0,0,0,1,8,118,50,31,0,1,0
267,0,0,1,0,8,235,37,29,1,1,1
268,1,0,0,0,8,361,28,27,0,1,4
269,1,0,0,0,8,184,27,21,0,0,0
270,1,0,0,0,9,179,38,31,0,0,0
271,0,0,0,1,9,179,38,31,0,0,0
272,0,0,1,0,9,289,33,30,0,2,1
273,0,0,0,0,9,235,43,38,0,1,0
274,1,0,0,0,9,246,41,23,0,0,0
275,0,0,0,1,9,291,40,25,0,1,1
276,0,0,0,0,9,231,39,35,0,2,2
277,0,0,0,0,9,291,32,23,0,0,0
278,1,0,0,0,9,179,38,31,0,0,0
279,1,0,0,0,9,246,41,23,0,0,0
280,0,0,0,1,9,179,38,31,0,0,0
281,0,0,0,1,9,291,40,25,0,1,1
282,0,0,0,1,9,260,36,23,0,4,0
283,0,0,0,1,9,235,43,38,0,1,0
284,0,0,0,1,9,118,50,31,0,1,0
285,0,0,0,0,9,235,43,38,0,1,0
286,0,0,0,1,9,291,40,25,0,1,1
287,1,0,0,0,9,291,40,25,0,1,1
288,1,0,0,0,9,179,38,31,0,0,0
289,0,0,0,1,10,289,33,30,0,2,1
290,0,0,0,1,10,235,37,29,1,1,1
291,0,0,0,1,10,289,33,30,0,2,1
292,0,0,0,1,10,289,33,30,0,2,1
293,0,0,0,0,10,118,50,31,0,1,0
294,0,0,0,0,10,248,47,32,0,2,1
295,1,0,0,0,10,179,30,19,1,0,0
296,1,0,0,0,10,118,37,28,0,0,0
297,0,0,0,1,10,369,31,25,0,3,0
298,0,0,0,1,10,179,38,31,0,0,0
299,1,0,0,0,10,179,30,19,1,0,0
300,0,0,0,0,10,235,43,38,0,1,0
301,0,0,1,0,10,289,33,30,0,2,1
302,0,0,0,1,10,260,36,23,0,4,0
303,0,0,0,0,10,235,43,38,0,1,0
304,0,0,0,1,10,235,43,38,0,1,0
305,0,0,0,1,10,235,43,38,0,1,0
306,0,0,0,1,10,118,50,31,0,1,0
307,0,0,0,1,10,291,40,25,0,1,1
308,0,0,0,1,10,179,30,19,1,0,0
309,0,0,0,1,10,118,50,31,0,1,0
310,1,0,0,0,10,361,28,27,0,1,4
311,0,0,0,0,10,260,36,23,0,4,0
312,0,0,0,0,10,291,40,25,0,1,1
313,0,0,0,0,10,157,29,22,0,0,0
314,1,0,0,0,10,179,30,19,1,0,0
315,1,0,0,0,10,179,30,19,1,0,0
316,0,0,0,1,10,118,50,31,0,1,0
317,1,0,0,0,11,118,37,28,0,0,0
318,0,0,0,1,11,248,47,32,0,2,1
319,1,0,0,0,11,179,38,31,0,0,0
320,0,0,0,1,11,260,36,23,0,4,0
321,0,0,0,1,11,291,40,25,0,1,1
322,1,0,0,0,11,378,36,21,0,2,4
323,1,0,0,0,11,155,34,25,0,2,0
324,0,0,0,1,11,235,43,38,0,1,0
325,0,0,0,0,11,330,28,25,1,0,0
326,0,0,1,0,11,235,37,29,1,1,1
327,1,0,0,0,11,118,37,28,0,0,0
328,0,0,0,1,11,235,37,29,1,1,1
329,0,0,0,1,11,179,38,31,0,0,0
330,1,0,0,0,11,246,41,23,0,0,0
331,1,0,0,0,11,291,40,25,0,1,1
332,1,0,0,0,11,246,41,23,0,0,0
333,0,0,0,1,11,179,38,31,0,0,0
334,1,0,0,0,11,260,36,23,0,4,0
335,0,1,0,0,11,260,36,23,0,4,0
336,0,0,0,0,11,378,36,21,0,2,4
337,0,0,0,0,11,279,39,24,0,2,0
338,0,0,0,1,11,179,38,31,0,0,0
339,1,0,0,0,12,225,28,24,0,1,2
340,0,0,0,1,12,179,38,31,0,0,0
341,0,0,0,1,12,179,38,31,0,0,0
342,0,0,0,1,12,235,37,29,1,1,1
343,0,0,0,1,12,118,50,31,0,1,0
344,0,0,0,1,12,260,36,23,0,4,0
345,1,0,0,0,12,246,41,23,0,0,0
346,0,0,0,1,12,179,38,31,0,0,0
347,0,0,0,1,12,179,38,31,0,0,0
348,0,0,0,1,12,179,30,19,1,0,0
349,0,0,0,1,12,118,37,28,0,0,0
350,0,0,0,1,12,235,37,29,1,1,1
351,0,0,0,1,12,179,38,31,0,0,0
352,1,0,0,0,12,235,43,38,0,1,0
353,1,0,0,0,12,235,37,29,1,1,1
354,0,0,0,1,12,260,36,23,0,4,0
355,0,0,0,1,12,157,29,22,0,0,0
356,0,0,0,1,12,179,38,31,0,0,0
357,0,0,1,0,12,289,33,30,0,2,1
358,0,0,0,1,1,225,28,24,0,1,2
359,0,0,1,0,1,118,37,28,0,0,0
360,0,0,0,1,1,155,34,25,0,2,0
361,1,0,0,0,1,235,37,29,1,1,1
362,0,0,0,1,1,155,34,25,0,2,0
363,0,0,0,1,1,289,33,30,0,2,1
364,1,0,0,0,1,291,40,25,0,1,1
365,0,0,0,1,1,235,43,38,0,1,0
366,0,0,0,1,1,118,50,31,0,1,0
367,0,0,0,1,1,179,38,31,0,0,0
368,0,0,0,1,1,179,38,31,0,0,0
369,0,0,0,1,2,118,37,28,0,0,0
370,0,0,0,1,2,179,38,31,0,0,0
371,1,0,0,0,2,225,28,24,0,1,2
372,0,0,0,1,2,289,33,30,0,2,1
373,0,0,0,1,2,260,36,23,0,4,0
374,0,0,0,1,2,179,38,31,0,0,0
375,0,0,0,1,2,179,38,31,0,0,0
376,0,0,0,1,2,179,38,31,0,0,0
377,1,0,0,0,2,179,38,31,0,0,0
378,0,0,0,1,2,246,41,23,0,0,0
379,0,0,0,1,2,179,38,31,0,0,0
380,0,0,0,1,2,189,33,25,0,2,2
381,0,0,0,1,2,179,38,31,0,0,0
382,0,0,0,1,2,246,41,23,0,0,0
383,0,0,0,1,2,291,40,25,0,1,1
384,1,0,0,0,2,157,29,22,0,0,0
385,0,0,0,1,2,179,38,31,0,0,0
386,0,0,0,1,2,179,38,31,0,0,0
387,1,0,0,0,2,246,41,23,0,0,0
388,0,0,0,1,2,179,38,31,0,0,0
389,0,0,0,1,2,179,38,31,0,0,0
390,0,0,1,0,3,118,37,28,0,0,0
391,0,0,1,0,3,246,41,23,0,0,0
392,0,0,0,1,3,246,41,23,0,0,0
393,0,0,0,1,3,260,36,23,0,4,0
394,0,0,0,1,3,179,38,31,0,0,0
395,0,0,0,1,3,235,37,29,1,1,1
396,0,0,0,1,3,179,40,22,1,2,0
397,0,0,0,1,3,378,36,21,0,2,4
398,0,0,0,1,3,179,38,31,0,0,0
399,0,0,0,1,3,361,28,27,0,1,4
400,0,0,0,0,3,369,31,25,0,3,0
401,0,0,1,0,3,235,37,29,1,1,1
402,0,0,0,1,3,118,50,31,0,1,0
403,1,0,0,0,3,118,50,31,0,1,0
404,1,0,0,0,3,118,50,31,0,1,0
405,0,0,0,0,3,235,37,29,1,1,1
406,0,0,0,0,3,246,41,23,0,0,0
407,0,0,0,0,3,118,50,31,0,1,0
408,0,0,0,1,3,179,38,31,0,0,0
409,0,0,0,1,3,289,33,30,0,2,1
410,0,0,1,0,3,260,36,23,0,4,0
411,0,0,0,1,3,246,41,23,0,0,0
412,0,0,0,1,4,179,38,31,0,0,0
413,0,0,0,1,4,260,36,23,0,4,0
414,0,0,0,1,4,330,28,25,1,0,0
415,0,0,0,1,4,369,31,25,0,3,0
416,0,0,0,1,4,248,47,32,0,2,1
417,0,0,0,1,4,330,28,25,1,0,0
418,0,0,0,1,4,179,38,31,0,0,0
419,0,0,0,1,4,118,50,31,0,1,0
420,1,0,0,0,4,118,50,31,0,1,0
421,0,0,0,1,4,300,43,25,0,2,1
422,0,0,0,1,4,260,36,23,0,4,0
423,0,0,0,1,4,179,38,31,0,0,0
424,1,0,0,0,4,118,37,28,0,0,0
425,1,0,0,0,5,235,43,38,0,1,0
426,0,0,0,1,5,248,47,32,0,2,1
427,1,0,0,0,5,369,31,25,0,3,0
428,0,0,0,1,5,179,30,19,1,0,0
429,0,0,0,1,5,179,38,31,0,0,0
430,0,0,0,1,5,361,28,27,0,1,4
431,0,0,0,1,5,260,36,23,0,4,0
432,1,0,0,0,5,179,40,22,1,2,0
433,1,0,0,0,5,179,40,22,1,2,0
434,0,0,1,0,5,228,58,22,0,2,1
435,0,0,0,1,5,225,28,24,0,1,2
436,1,0,0,0,5,330,28,25,1,0,0
437,0,0,0,1,5,179,30,19,1,0,0
438,0,0,0,1,5,118,37,28,0,0,0
439,1,0,0,0,5,235,37,29,1,1,1
440,0,0,0,1,5,179,30,19,1,0,0
441,0,0,0,1,6,118,37,28,0,0,0
442,0,0,0,1,6,179,38,31,0,0,0
443,0,0,0,1,6,118,37,28,0,0,0
444,0,0,0,1,6,225,28,24,0,1,2
445,0,0,0,1,6,260,36,23,0,4,0
446,0,0,0,0,6,179,38,31,0,0,0
447,1,0,0,0,6,291,40,25,0,1,1
448,0,0,0,1,6,179,38,31,0,0,0
449,0,0,0,1,6,246,41,23,0,0,0
450,0,0,0,1,6,179,38,31,0,0,0
451,0,0,0,1,6,235,43,38,0,1,0
452,0,0,0,1,6,179,38,31,0,0,0
453,0,0,0,1,6,225,28,24,0,1,2
454,0,0,0,1,6,118,50,31,0,1,0
455,1,0,0,0,6,179,38,31,0,0,0
456,0,0,1,0,6,179,30,19,1,0,0
457,0,0,0,1,6,246,41,23,0,0,0
458,1,0,0,0,6,330,28,25,1,0,0
459,1,0,0,0,6,235,37,29,1,1,1
460,0,0,0,1,7,179,30,19,1,0,0
461,0,0,0,1,7,225,28,24,0,1,2
462,1,0,0,0,7,260,36,23,0,4,0
463,1,0,0,0,7,268,33,25,1,0,0
464,0,0,0,1,7,330,28,25,1,0,0
465,0,0,0,1,7,118,37,28,0,0,0
466,0,0,0,1,7,260,36,23,0,4,0
467,0,0,0,1,7,118,37,28,0,0,0
468,0,1,0,0,7,300,43,25,0,2,1
469,0,0,0,1,7,235,48,33,0,1,5
470,0,0,0,1,7,246,41,23,0,0,0
471,1,0,0,0,7,225,28,24,0,1,2
472,0,0,0,1,7,179,38,31,0,0,0
473,0,0,0,1,7,118,50,31,0,1,0
474,0,0,0,1,7,361,28,27,0,1,4
475,0,0,0,1,7,289,33,30,0,2,1
476,0,0,0,1,7,235,43,38,0,1,0
477,0,0,0,1,7,246,41,23,0,0,0
478,0,0,0,1,7,291,40,25,0,1,1
479,0,0,0,1,7,279,39,24,0,2,0
480,0,0,0,1,8,179,38,31,0,0,0
481,0,0,0,1,8,179,40,22,1,2,0
482,0,0,0,1,8,246,41,23,0,0,0
483,0,0,0,1,8,118,37,28,0,0,0
484,0,0,0,1,8,289,33,30,0,2,1
485,0,0,0,1,8,235,43,38,0,1,0
486,0,0,0,1,8,291,40,25,0,1,1
487,0,0,0,1,8,179,38,31,0,0,0
488,0,0,0,1,8,179,40,22,1,2,0
489,0,0,0,1,8,330,28,25,1,0,0
490,0,0,0,1,8,235,37,29,1,1,1
491,0,0,0,1,8,246,41,23,0,0,0
492,0,0,0,1,8,118,37,28,0,0,0
493,0,0,0,1,8,291,40,25,0,1,1
494,0,0,0,1,8,260,36,23,0,4,0
495,0,0,0,1,9,246,41,23,0,0,0
496,0,0,0,1,9,246,41,23,0,0,0
497,0,0,0,1,9,118,37,28,0,0,0
498,0,0,0,1,9,155,34,25,0,2,0
499,0,0,0,1,9,291,40,25,0,1,1
500,0,0,0,1,9,179,30,19,1,0,0
501,0,0,0,1,9,248,47,32,0,2,1
502,0,0,0,1,9,179,38,31,0,0,0
503,0,0,0,1,9,225,28,24,0,1,2
504,0,0,0,1,9,179,30,19,1,0,0
505,0,0,0,1,9,369,31,25,0,3,0
506,0,0,0,1,9,361,28,27,0,1,4
507,1,0,0,0,10,289,49,36,0,0,2
508,1,0,0,0,10,235,32,25,1,0,0
509,0,0,0,1,10,246,41,23,0,0,0
510,1,0,0,0,10,289,49,36,0,0,2
511,0,0,0,1,10,291,40,25,0,1,1
512,0,0,0,1,10,118,37,28,0,0,0
513,0,0,0,1,10,289,49,36,0,0,2
514,0,0,0,1,10,291,40,25,0,1,1
515,0,0,0,1,10,225,28,24,0,1,2
516,0,0,0,1,10,369,31,25,0,3,0
517,0,0,0,1,10,369,31,25,0,3,0
518,0,0,0,1,10,225,28,24,0,1,2
519,0,0,0,1,10,369,31,25,0,3,0
520,0,0,0,1,10,179,38,31,0,0,0
521,1,0,0,0,10,228,58,22,0,2,1
522,0,0,0,1,10,291,40,25,0,1,1
523,1,0,0,0,10,369,31,25,0,3,0
524,1,0,0,0,10,225,28,24,0,1,2
525,1,0,0,0,10,369,31,25,0,3,0
526,1,0,0,0,10,225,28,24,0,1,2
527,0,0,0,1,10,189,33,25,0,2,2
528,1,0,0,0,10,235,32,25,1,0,0
529,1,0,0,0,10,248,47,32,0,2,1
530,0,0,0,0,10,225,28,24,0,1,2
531,1,0,0,0,10,225,28,24,0,1,2
532,0,0,1,0,11,179,38,31,0,0,0
533,0,0,0,1,11,118,37,28,0,0,0
534,1,0,0,0,11,330,28,25,1,0,0
535,0,0,0,1,11,179,38,31,0,0,0
536,1,0,0,0,11,118,37,28,0,0,0
537,0,0,0,1,11,289,33,30,0,2,1
538,1,0,0,0,11,235,32,25,1,0,0
539,0,0,0,1,11,225,28,24,0,1,2
540,0,0,0,1,11,361,28,27,0,1,4
541,0,0,0,1,11,291,40,25,0,1,1
542,1,0,0,0,11,118,37,28,0,0,0
543,1,0,0,0,11,225,28,24,0,1,2
544,0,0,0,1,11,179,38,31,0,0,0
545,0,0,0,1,11,118,37,28,0,0,0
546,1,0,0,0,11,118,37,28,0,0,0
547,0,0,0,1,11,225,28,24,0,1,2
548,0,0,0,0,11,291,40,25,0,1,1
549,0,0,0,0,11,289,33,30,0,2,1
550,1,0,0,0,11,248,47,32,0,2,1
551,0,0,0,0,11,235,43,38,0,1,0
552,0,0,0,1,11,225,28,24,0,1,2
553,0,0,0,1,11,369,31,25,0,3,0
554,0,0,0,1,11,361,28,27,0,1,4
555,1,0,0,0,12,179,38,31,0,0,0
556,0,0,0,1,12,291,40,25,0,1,1
557,0,0,0,1,12,225,28,24,0,1,2
558,1,0,0,0,12,179,30,19,1,0,0
559,0,0,0,1,12,225,28,24,0,1,2
560,0,0,0,1,12,225,28,24,0,1,2
561,1,0,0,0,12,361,28,27,0,1,4
562,0,0,1,0,12,179,40,22,1,2,0
563,0,0,0,1,12,235,43,38,0,1,0
564,0,0,1,0,12,233,31,21,1,1,8
565,1,0,0,0,12,179,30,19,1,0,0
566,0,0,0,1,12,225,28,24,0,1,2
567,0,0,0,1,12,225,28,24,0,1,2
568,0,0,0,1,12,225,28,24,0,1,2
569,0,0,1,0,12,155,34,25,0,2,0
570,1,0,0,0,1,179,30,19,1,0,0
571,1,0,0,0,1,179,30,19,1,0,0
572,0,0,0,1,1,179,40,22,1,2,0
573,0,0,0,1,1,179,40,22,1,2,0
574,1,0,0,0,1,179,30,19,1,0,0
575,0,0,0,1,1,179,40,22,1,2,0
576,1,0,0,0,1,289,49,36,0,0,2
577,0,0,1,0,1,179,40,22,1,2,0
578,0,0,0,1,1,179,30,19,1,0,0
579,0,0,1,0,1,155,34,25,0,2,0
580,0,0,0,1,1,179,30,19,1,0,0
581,0,0,0,1,1,179,38,31,0,0,0
582,1,0,0,0,1,289,33,30,0,2,1
583,0,0,0,1,1,179,38,31,0,0,0
584,0,0,0,1,1,179,38,31,0,0,0
585,1,0,0,0,2,179,38,31,0,0,0
586,0,0,0,1,2,225,28,24,0,1,2
587,1,0,0,0,2,248,47,32,0,2,1
588,0,0,0,1,2,179,38,31,0,0,0
589,0,0,0,1,2,225,28,24,0,1,2
590,0,0,0,1,2,179,38,31,0,0,0
591,0,0,0,1,2,179,30,19,1,0,0
592,0,0,0,1,2,225,41,28,1,2,2
593,0,0,0,1,2,179,38,31,0,0,0
594,0,0,1,0,2,233,31,21,1,1,8
595,0,0,0,1,2,179,38,31,0,0,0
596,1,0,0,0,2,225,28,24,0,1,2
597,0,0,0,1,2,179,38,31,0,0,0
598,0,0,0,1,2,179,38,31,0,0,0
599,0,0,0,1,2,225,28,24,0,1,2
600,1,0,0,0,2,179,30,19,1,0,0
601,0,0,0,1,2,179,40,22,1,2,0
602,0,0,0,1,2,179,38,31,0,0,0
603,1,0,0,0,2,233,31,21,1,1,8
604,0,0,0,1,2,179,30,19,1,0,0
605,0,0,0,1,2,179,38,31,0,0,0
606,1,0,0,0,2,179,38,31,0,0,0
607,0,0,0,1,2,179,38,31,0,0,0
608,0,0,0,1,2,155,34,25,0,2,0
609,0,0,0,1,2,235,32,25,1,0,0
610,0,0,0,1,2,179,38,31,0,0,0
611,1,0,0,0,2,225,28,24,0,1,2
612,0,0,0,1,2,179,38,31,0,0,0
613,0,0,0,1,2,248,47,32,0,2,1
614,0,0,0,1,2,225,28,24,0,1,2
615,0,0,0,1,2,179,38,31,0,0,0
616,0,0,0,1,2,179,38,31,0,0,0
617,0,0,0,1,2,235,32,25,1,0,0
618,0,0,0,1,3,179,38,31,0,0,0
619,0,0,0,1,3,248,47,32,0,2,1
620,0,0,0,1,3,228,58,22,0,2,1
621,0,0,0,1,3,248,47,32,0,2,1
622,1,0,0,0,3,228,58,22,0,2,1
623,0,0,0,1,3,179,38,31,0,0,0
624,0,0,0,1,3,225,28,24,0,1,2
625,0,0,0,1,3,179,38,31,0,0,0
626,0,0,0,1,3,225,28,24,0,1,2
627,0,0,0,1,3,179,30,19,1,0,0
628,0,0,0,1,3,235,32,25,1,0,0
629,0,0,1,0,3,361,28,27,0,1,4
630,1,0,0,0,3,179,38,31,0,0,0
631,0,0,0,1,3,179,38,31,0,0,0
632,0,0,0,1,3,179,38,31,0,0,0
633,0,0,0,1,3,179,30,19,1,0,0
634,1,0,0,0,3,179,38,31,0,0,0
635,1,0,0,0,3,248,47,32,0,2,1
636,0,0,0,1,3,179,38,31,0,0,0
637,1,0,0,0,3,225,28,24,0,1,2
638,0,0,0,1,3,179,38,31,0,0,0
639,0,0,0,1,3,289,33,30,0,2,1
640,0,0,0,1,3,228,58,22,0,2,1
641,0,0,0,1,3,179,38,31,0,0,0
642,0,0,0,1,3,248,47,32,0,2,1
643,0,0,0,1,3,179,38,31,0,0,0
644,0,0,0,1,3,179,30,19,1,0,0
645,0,0,0,1,3,179,38,31,0,0,0
646,0,0,0,1,3,179,38,31,0,0,0
647,0,0,0,1,3,118,46,25,0,2,0
648,1,0,0,0,3,155,34,25,0,2,0
649,0,0,0,1,3,179,38,31,0,0,0
650,0,0,0,1,3,179,38,31,0,0,0
651,1,0,0,0,3,179,30,19,1,0,0
652,0,0,1,0,3,289,33,30,0,2,1
653,0,0,0,1,3,369,31,25,0,3,0
654,1,0,0,0,4,225,28,24,0,1,2
655,1,0,0,0,4,118,37,28,0,0,0
656,0,0,1,0,4,361,28,27,0,1,4
657,0,0,1,0,4,248,47,32,0,2,1
658,1,0,0,0,4,189,33,25,0,2,2
659,0,0,0,1,4,179,30,19,1,0,0

In [301]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [302]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [303]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [304]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [305]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [306]:
 absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [307]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [308]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [309]:

from sklearn.model_selection import train_test_split

In [310]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
          0.88046927, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976]]),
 array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  3.70119207],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
          0.88046927, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661]]),
 array([1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
        0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
        1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
        0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
        1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1])]

In [311]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [312]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)

In [313]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)

In [314]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [315]:
reg = LogisticRegression()

In [316]:
reg.fit(x_train,y_train)

LogisticRegression()

In [317]:
reg.score(x_train,y_train)

0.7839285714285714

In [318]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0])

In [319]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [320]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True])

In [321]:
np.sum((model_outputs==y_train))

439

In [322]:
model_outputs.shape[0]

560

In [323]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7839285714285714

In [324]:
reg.intercept_

array([-0.22375632])

In [325]:
reg.coef_

array([[ 2.0695214 ,  0.33581057,  1.56203942,  1.31277993,  0.18469755,
         0.69126151, -0.19828303,  0.32435951, -0.12665599,  0.37017705,
        -0.32535864]])

In [326]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [327]:
feature_name = unscaled_inputs.columns.values

In [328]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

              Feature name  Coefficient
0                 Reason_1     2.069521
1                 Reason_2     0.335811
2                 Reason_3     1.562039
3                 Reason_4     1.312780
4              Month Value     0.184698
5   Transportation Expense     0.691262
6                      Age    -0.198283
7          Body Mass Index     0.324360
8                Education    -0.126656
9                 Children     0.370177
10                    Pets    -0.325359

In [329]:
summary_table.index = summary_table.index + 1

summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

summary_table = summary_table.sort_index()
summary_table

              Feature name  Coefficient
0                Intercept    -0.223756
1                 Reason_1     2.069521
2                 Reason_2     0.335811
3                 Reason_3     1.562039
4                 Reason_4     1.312780
5              Month Value     0.184698
6   Transportation Expense     0.691262
7                      Age    -0.198283
8          Body Mass Index     0.324360
9                Education    -0.126656
10                Children     0.370177
11                    Pets    -0.325359

In [330]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [331]:
summary_table

              Feature name  Coefficient  Odds_ratio
0                Intercept    -0.223756    0.799510
1                 Reason_1     2.069521    7.921031
2                 Reason_2     0.335811    1.399074
3                 Reason_3     1.562039    4.768536
4                 Reason_4     1.312780    3.716491
5              Month Value     0.184698    1.202855
6   Transportation Expense     0.691262    1.996232
7                      Age    -0.198283    0.820138
8          Body Mass Index     0.324360    1.383144
9                Education    -0.126656    0.881037
10                Children     0.370177    1.447991
11                    Pets    -0.325359    0.722268

In [332]:
summary_table.sort_values('Odds_ratio', ascending=False)

              Feature name  Coefficient  Odds_ratio
1                 Reason_1     2.069521    7.921031
3                 Reason_3     1.562039    4.768536
4                 Reason_4     1.312780    3.716491
6   Transportation Expense     0.691262    1.996232
10                Children     0.370177    1.447991
2                 Reason_2     0.335811    1.399074
8          Body Mass Index     0.324360    1.383144
5              Month Value     0.184698    1.202855
9                Education    -0.126656    0.881037
7                      Age    -0.198283    0.820138
0                Intercept    -0.223756    0.799510
11                    Pets    -0.325359    0.722268

In [333]:
reg.score(x_test,y_test)

0.7357142857142858

In [334]:
predicted_proba = reg.predict_proba(x_test)

predicted_proba

array([[0.70804629, 0.29195371],
       [0.57178351, 0.42821649],
       [0.39895299, 0.60104701],
       [0.78714111, 0.21285889],
       [0.06691516, 0.93308484],
       [0.31109284, 0.68890716],
       [0.28582378, 0.71417622],
       [0.08093986, 0.91906014],
       [0.79926793, 0.20073207],
       [0.7496687 , 0.2503313 ],
       [0.46772305, 0.53227695],
       [0.18449682, 0.81550318],
       [0.04086632, 0.95913368],
       [0.75596678, 0.24403322],
       [0.23709315, 0.76290685],
       [0.54140798, 0.45859202],
       [0.53354387, 0.46645613],
       [0.52039975, 0.47960025],
       [0.40507469, 0.59492531],
       [0.02759587, 0.97240413],
       [0.70148836, 0.29851164],
       [0.78714111, 0.21285889],
       [0.40545618, 0.59454382],
       [0.40545618, 0.59454382],
       [0.17391667, 0.82608333],
       [0.75362875, 0.24637125],
       [0.48817233, 0.51182767],
       [0.88053255, 0.11946745],
       [0.13059235, 0.86940765],
       [0.78714111, 0.21285889],
       [0.62247425, 0.37752575],
       [0.30437845, 0.69562155],
       [0.28895164, 0.71104836],
       [0.44157966, 0.55842034],
       [0.78714111, 0.21285889],
       [0.43705325, 0.56294675],
       [0.79067389, 0.20932611],
       [0.18986981, 0.81013019],
       [0.58710261, 0.41289739],
       [0.36998588, 0.63001412],
       [0.79584274, 0.20415726],
       [0.57848411, 0.42151589],
       [0.77268351, 0.22731649],
       [0.89513347, 0.10486653],
       [0.14276767, 0.85723233],
       [0.34529847, 0.65470153],
       [0.29370238, 0.70629762],
       [0.70804629, 0.29195371],
       [0.78792994, 0.21207006],
       [0.80427711, 0.19572289],
       [0.43450126, 0.56549874],
       [0.92225898, 0.07774102],
       [0.31109284, 0.68890716],
       [0.73029003, 0.26970997],
       [0.14019617, 0.85980383],
       [0.54578776, 0.45421224],
       [0.06949094, 0.93050906],
       [0.78211875, 0.21788125],
       [0.91468256, 0.08531744],
       [0.91047636, 0.08952364],
       [0.29440565, 0.70559435],
       [0.3225053 , 0.6774947 ],
       [0.71278024, 0.28721976],
       [0.13921991, 0.86078009],
       [0.81010673, 0.18989327],
       [0.72936044, 0.27063956],
       [0.98595531, 0.01404469],
       [0.79067389, 0.20932611],
       [0.18707135, 0.81292865],
       [0.71499343, 0.28500657],
       [0.79067389, 0.20932611],
       [0.93124347, 0.06875653],
       [0.07140162, 0.92859838],
       [0.52206954, 0.47793046],
       [0.36134577, 0.63865423],
       [0.78714111, 0.21285889],
       [0.14962662, 0.85037338],
       [0.26408704, 0.73591296],
       [0.22931828, 0.77068172],
       [0.32006017, 0.67993983],
       [0.76328838, 0.23671162],
       [0.98845557, 0.01154443],
       [0.78211875, 0.21788125],
       [0.22297761, 0.77702239],
       [0.55457206, 0.44542794],
       [0.90100263, 0.09899737],
       [0.26777377, 0.73222623],
       [0.40545618, 0.59454382],
       [0.94848341, 0.05151659],
       [0.30437845, 0.69562155],
       [0.85602571, 0.14397429],
       [0.86122209, 0.13877791],
       [0.77817196, 0.22182804],
       [0.72936044, 0.27063956],
       [0.7496687 , 0.2503313 ],
       [0.12573789, 0.87426211],
       [0.69702716, 0.30297284],
       [0.21427718, 0.78572282],
       [0.76029427, 0.23970573],
       [0.81248944, 0.18751056],
       [0.33737954, 0.66262046],
       [0.30437845, 0.69562155],
       [0.27918665, 0.72081335],
       [0.24273428, 0.75726572],
       [0.53520877, 0.46479123],
       [0.4957175 , 0.5042825 ],
       [0.71882631, 0.28117369],
       [0.12573789, 0.87426211],
       [0.20662001, 0.79337999],
       [0.86740544, 0.13259456],
       [0.98959909, 0.01040091],
       [0.07487408, 0.92512592],
       [0.2494824 , 0.7505176 ],
       [0.65886996, 0.34113004],
       [0.45006774, 0.54993226],
       [0.42034788, 0.57965212],
       [0.14588413, 0.85411587],
       [0.15471885, 0.84528115],
       [0.45730036, 0.54269964],
       [0.69032997, 0.30967003],
       [0.73964286, 0.26035714],
       [0.862864  , 0.137136  ],
       [0.14806763, 0.85193237],
       [0.57848411, 0.42151589],
       [0.78714111, 0.21285889],
       [0.65838291, 0.34161709],
       [0.79584274, 0.20415726],
       [0.90442096, 0.09557904],
       [0.22848616, 0.77151384],
       [0.70148836, 0.29851164],
       [0.35778052, 0.64221948],
       [0.79584274, 0.20415726],
       [0.69702716, 0.30297284],
       [0.65838291, 0.34161709],
       [0.74404968, 0.25595032],
       [0.45006774, 0.54993226],
       [0.52039975, 0.47960025],
       [0.70412694, 0.29587306],
       [0.76029427, 0.23970573],
       [0.52206954, 0.47793046]])

In [335]:
predicted_proba.shape

(140, 2)

In [336]:
predicted_proba[:,1]

array([0.29195371, 0.42821649, 0.60104701, 0.21285889, 0.93308484,
       0.68890716, 0.71417622, 0.91906014, 0.20073207, 0.2503313 ,
       0.53227695, 0.81550318, 0.95913368, 0.24403322, 0.76290685,
       0.45859202, 0.46645613, 0.47960025, 0.59492531, 0.97240413,
       0.29851164, 0.21285889, 0.59454382, 0.59454382, 0.82608333,
       0.24637125, 0.51182767, 0.11946745, 0.86940765, 0.21285889,
       0.37752575, 0.69562155, 0.71104836, 0.55842034, 0.21285889,
       0.56294675, 0.20932611, 0.81013019, 0.41289739, 0.63001412,
       0.20415726, 0.42151589, 0.22731649, 0.10486653, 0.85723233,
       0.65470153, 0.70629762, 0.29195371, 0.21207006, 0.19572289,
       0.56549874, 0.07774102, 0.68890716, 0.26970997, 0.85980383,
       0.45421224, 0.93050906, 0.21788125, 0.08531744, 0.08952364,
       0.70559435, 0.6774947 , 0.28721976, 0.86078009, 0.18989327,
       0.27063956, 0.01404469, 0.20932611, 0.81292865, 0.28500657,
       0.20932611, 0.06875653, 0.92859838, 0.47793046, 0.63865423,
       0.21285889, 0.85037338, 0.73591296, 0.77068172, 0.67993983,
       0.23671162, 0.01154443, 0.21788125, 0.77702239, 0.44542794,
       0.09899737, 0.73222623, 0.59454382, 0.05151659, 0.69562155,
       0.14397429, 0.13877791, 0.22182804, 0.27063956, 0.2503313 ,
       0.87426211, 0.30297284, 0.78572282, 0.23970573, 0.18751056,
       0.66262046, 0.69562155, 0.72081335, 0.75726572, 0.46479123,
       0.5042825 , 0.28117369, 0.87426211, 0.79337999, 0.13259456,
       0.01040091, 0.92512592, 0.7505176 , 0.34113004, 0.54993226,
       0.57965212, 0.85411587, 0.84528115, 0.54269964, 0.30967003,
       0.26035714, 0.137136  , 0.85193237, 0.42151589, 0.21285889,
       0.34161709, 0.20415726, 0.09557904, 0.77151384, 0.29851164,
       0.64221948, 0.20415726, 0.30297284, 0.34161709, 0.25595032,
       0.54993226, 0.47960025, 0.29587306, 0.23970573, 0.47793046])

In [337]:
import pickle

In [338]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [339]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)